'use client';
import {useEffect,useState} from 'react';
import {supabaseBrowser} from '@/lib/supabase/browser';

export default function ResetPassword(){
 const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [busy,setBusy]=useState(false);const [ready,setReady]=useState(false);const [checking,setChecking]=useState(true);const [message,setMessage]=useState('');const [error,setError]=useState('');
 useEffect(()=>{const supabase=supabaseBrowser();let active=true;const {data}=supabase.auth.onAuthStateChange((event)=>{if(active&&(event==='PASSWORD_RECOVERY'||event==='SIGNED_IN'))setReady(true)});(async()=>{const code=new URLSearchParams(location.search).get('code');let exchangeError=null;if(code){const result=await supabase.auth.exchangeCodeForSession(code);exchangeError=result.error}const {data:session}=await supabase.auth.getSession();if(active){if(session.session)setReady(true);else if(exchangeError)setError('رابط الاستعادة غير صالح أو انتهت صلاحيته. / The recovery link is invalid or expired.');setChecking(false)}})().catch(()=>{if(active){setChecking(false);setError('تعذر التحقق من رابط الاستعادة. / Unable to verify the recovery link.')}});return()=>{active=false;data.subscription.unsubscribe()}},[]);
 async function submit(){setError('');setMessage('');if(password.length<8){setError('Password must be at least 8 characters.');return}if(password!==confirm){setError('Passwords do not match.');return}setBusy(true);const {error}=await supabaseBrowser().auth.updateUser({password});setBusy(false);if(error){setError('Unable to update password. Please request a new reset link.');return}setMessage('Password updated. You can now sign in.');setTimeout(()=>{location.href='/ar/login'},700)}
 return <main className="container" style={{maxWidth:560,paddingTop:40,paddingBottom:60}}><div className="card hero"><div style={{textAlign:'center',marginBottom:22}}><span className="pill">ZakatFlow</span><h1>إعادة تعيين كلمة المرور / Reset password</h1><p className="muted">اختر كلمة مرور جديدة لحسابك. / Choose a new password for your account.</p></div>{checking&&<p className="muted" role="status">جارٍ التحقق من جلسة الاستعادة… / Checking recovery session…</p>}{!checking&&!ready&&!message&&<p className="muted" role="status">افتح هذه الصفحة من رابط الاستعادة في البريد. / Open this page from the password reset email.</p>}{ready&&<div style={{display:'grid',gap:12}}><label>كلمة المرور الجديدة / New password<input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} style={{width:'100%',padding:12,marginTop:8}}/></label><label>تأكيد كلمة المرور / Confirm password<input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} style={{width:'100%',padding:12,marginTop:8}}/></label><button className="btn" onClick={submit} disabled={busy}>{busy?'جارٍ التحديث… / Updating…':'تحديث كلمة المرور / Update password'}</button></div>}{error&&<p role="alert" style={{color:'#b42318'}}>{error}</p>}{message&&<p role="status" style={{color:'#16794c'}}>{message}</p>}</div></main>
}
