import Decimal from 'decimal.js';
import { requireUser } from './auth';
import { calculateAssessment } from '@/engine/assessment';
import { calculateHawl } from '@/engine/hawl';
import { fetchReferenceMetalPrices } from './reference-prices';

export async function listAssessments(){const {supabase,user}=await requireUser();const {data,error}=await supabase.from('zakat_assessments').select('*').eq('user_id',user.id).order('assessment_date',{ascending:false});if(error)throw error;return data;}
export type AssessmentRequest={assessment_date:string;valuation_date?:string;nisab_standard?:'GOLD'|'SILVER';method_id?:string;gold_price?:number;silver_price?:number;price_currency?:string;fx_rate?:number;price_mode?:'REFERENCE'|'MANUAL';price_source?:string};
export async function calculateAndSaveAssessment(input:AssessmentRequest){
 const {supabase,user}=await requireUser();const valuationDate=input.valuation_date??input.assessment_date;const priceMode=input.price_mode??'MANUAL';
 const {data:profile,error:pe}=await supabase.from('profiles').select('base_currency,zakat_method_id,nisab_standard').eq('id',user.id).single();if(pe)throw pe;const methodId=input.method_id??profile.zakat_method_id;if(!methodId)throw new Error('ZAKAT_METHOD_NOT_CONFIGURED');
 const {data:method,error:me}=await supabase.from('zakat_methods').select('*').eq('id',methodId).single();if(me)throw me;
 const {data:lots,error:le}=await supabase.from('lots').select('*,asset_accounts(name,asset_type,currency,is_zakatable,metadata),transactions!lots_source_transaction_id_fkey(id,transaction_date)').eq('user_id',user.id).gt('remaining_quantity',0);if(le)throw le;
 const baseCurrency=profile.base_currency;const standard=input.nisab_standard??profile.nisab_standard??'SILVER';
 let priceQuery=supabase.from('market_prices').select('*').eq('valuation_date',valuationDate).in('asset_type',['GOLD','SILVER']).order('created_at',{ascending:false});if(input.price_source)priceQuery=priceQuery.eq('source',input.price_source);let {data:prices}=await priceQuery;
 if(priceMode==='REFERENCE'&&(!(prices??[]).length)){const refs=await fetchReferenceMetalPrices(valuationDate);if(refs.length){const {error:priceInsertError}=await supabase.from('market_prices').insert(refs.map(x=>({asset_type:x.metal,instrument_code:x.metal==='GOLD'?'XAU':'XAG',price_per_unit:x.pricePerGram,currency:x.currency,valuation_date:x.valuationDate,source:x.source})));if(priceInsertError)throw priceInsertError;let q=supabase.from('market_prices').select('*').eq('valuation_date',valuationDate).in('asset_type',['GOLD','SILVER']).order('created_at',{ascending:false});if(input.price_source)q=q.eq('source',input.price_source);prices=(await q).data;}}
 const refGold=Number(prices?.find((p:any)=>p.asset_type==='GOLD')?.price_per_unit??0),refSilver=Number(prices?.find((p:any)=>p.asset_type==='SILVER')?.price_per_unit??0);const goldPrice=priceMode==='REFERENCE'?refGold:(input.gold_price??0),silverPrice=priceMode==='REFERENCE'?refSilver:(input.silver_price??0);if((standard==='GOLD'&&goldPrice<=0)||(standard==='SILVER'&&silverPrice<=0))throw new Error(priceMode==='REFERENCE'?'REFERENCE_PRICE_NOT_FOUND':'NISAB_PRICE_REQUIRED');const nisabValue=new Decimal(standard==='GOLD'?85:595).mul(standard==='GOLD'?goldPrice:silverPrice);
 const candidates=(lots??[]).filter((lot:any)=>lot.asset_accounts?.is_zakatable===true&&!!lot.hawl_start_date).map((lot:any)=>{const account=lot.asset_accounts;let value=new Decimal(lot.remaining_value_base||0);let purity=new Decimal(1);if(account?.asset_type==='GOLD'){const karat=Number(account?.metadata?.karat??24);purity=new Decimal(karat>0&&karat<=24?karat/24:1);if(goldPrice<=0)throw new Error('GOLD_PRICE_REQUIRED');value=new Decimal(lot.remaining_quantity).mul(goldPrice).mul(purity).mul(input.fx_rate??1)}else if(account?.asset_type==='SILVER'){const raw=Number(account?.metadata?.purity??account?.metadata?.karat??999),p=raw>1?raw/1000:raw;purity=new Decimal(p>0&&p<=1?p:1);if(silverPrice<=0)throw new Error('SILVER_PRICE_REQUIRED');value=new Decimal(lot.remaining_quantity).mul(silverPrice).mul(purity).mul(input.fx_rate??1)}const assessment=new Date(input.assessment_date+'T00:00:00Z'),start=new Date(lot.hawl_start_date+'T00:00:00Z');const hawl=calculateHawl(method.calendar_type==='GREGORIAN'?'GREGORIAN':'HIJRI_TABULAR',start,assessment);return{lotId:lot.id,transactionId:lot.source_transaction_id,assetName:account?.name,assetType:account?.asset_type,marketValueBase:value,hawlCompleted:hawl.completed,quantity:lot.remaining_quantity,purity:purity.toString(),valuationPrice:account?.asset_type==='GOLD'?goldPrice:account?.asset_type==='SILVER'?silverPrice:null,valuationCurrency:baseCurrency,fxRate:input.fx_rate??1,hawlStartDate:lot.hawl_start_date,hawlDueDate:hawl.dueDate.toISOString().slice(0,10)}}).filter((x:any)=>x.marketValueBase.gt(0));
 const calc=calculateAssessment(candidates,nisabValue,method.zakat_rate);const snapshot={assessmentDate:input.assessment_date,valuationDate,methodCode:method.code,methodVersion:method.version,calendarType:method.calendar_type,nisabStandard:standard,nisabValue:nisabValue.toString(),priceMode,priceSource:priceMode==='REFERENCE'?(input.price_source??prices?.[0]?.source??'market_prices'):'USER_MANUAL',prices:{gold:goldPrice,silver:silverPrice},fxRate:input.fx_rate??1,candidateLots:candidates.length,calculatedAt:new Date().toISOString()};
 const {data:assessment,error:ae}=await supabase.from('zakat_assessments').insert({user_id:user.id,assessment_date:input.assessment_date,valuation_date:valuationDate,method_id:method.id,nisab_standard:standard,nisab_quantity:standard==='GOLD'?85:595,nisab_value_base:nisabValue.toString(),total_zakatable_value:calc.totalEligibleValue.toString(),zakat_rate:method.zakat_rate,zakat_due:calc.zakatDue.toString(),currency:baseCurrency,status:'CALCULATED',method_version:method.version,calculation_snapshot:snapshot}).select().single();if(ae)throw ae;
 const lines=candidates.map((c:any,i:number)=>({assessment_id:assessment.id,lot_id:c.lotId,quantity:c.quantity,valuation_price:c.valuationPrice,valuation_currency:c.valuationCurrency,fx_rate:c.fxRate,market_value:c.marketValueBase.toString(),eligible_value:calc.lines[i].eligibleValue.toString(),zakat_amount:calc.lines[i].zakatAmount.toString(),eligibility_status:calc.lines[i].status,reason_code:calc.lines[i].status,explanation:`${c.assetName??'Asset'} → Lot ${c.lotId}: ${calc.lines[i].explanation}${c.assetType==='GOLD'||c.assetType==='SILVER'?` Purity factor ${c.purity}.`:''}`}));const {error:lineError}=await supabase.from('zakat_assessment_lines').insert(lines);if(lineError)throw lineError;await supabase.from('audit_logs').insert({user_id:user.id,entity_type:'zakat_assessment',entity_id:assessment.id,action:'CREATE_SNAPSHOT',new_data:assessment});return{assessment,lines};
}
export async function confirmAssessment(id:string){const {supabase,user}=await requireUser();const {data,error}=await supabase.from('zakat_assessments').update({status:'CONFIRMED'}).eq('id',id).eq('user_id',user.id).eq('status','CALCULATED').select().single();if(error)throw error;await supabase.from('audit_logs').insert({user_id:user.id,entity_type:'zakat_assessment',entity_id:id,action:'CONFIRM',new_data:data});return data;}
