import Decimal from 'decimal.js';
import { requireUser } from './auth';
import { calculateAssessment } from '@/engine/assessment';
import { calculateHawl } from '@/engine/hawl';
import { fetchReferenceMetalPrices } from './reference-prices';
import {assessmentRequestSchema,nisabFromPrice,frozenLotValuation,type FrozenMetalPrice} from '@/lib/zakat-valuation';

export async function listAssessments(){const {supabase,user}=await requireUser();const {data,error}=await supabase.from('zakat_assessments').select('*').eq('user_id',user.id).order('assessment_date',{ascending:false});if(error)throw error;return data;}
export type AssessmentRequest={assessment_date:string;valuation_date?:string;nisab_standard?:'GOLD'|'SILVER';method_id?:string;gold_price?:number;silver_price?:number;price_currency?:string;fx_rate?:number;price_mode?:'REFERENCE'|'MANUAL';price_source?:string;nisab_reached_date?:string;nisab_start_method?:'MANUAL'|'HISTORICAL_RECORDED'};
function historicalNisabDate(lots:any[],threshold:Decimal,assessmentDate:string){const events=lots.filter((l:any)=>l.asset_accounts?.is_zakatable===true&&l.acquisition_date&&l.acquisition_date<=assessmentDate).map((l:any)=>({date:l.acquisition_date,value:new Decimal(l.original_value_base??l.remaining_value_base??0)})).filter((x:any)=>x.value.gt(0)).sort((a:any,b:any)=>a.date.localeCompare(b.date));let pool=new Decimal(0);for(const e of events){pool=pool.add(e.value);if(pool.gte(threshold))return e.date}return null}
export async function calculateAndSaveAssessment(request:AssessmentRequest,revisionOf?:string){
 const input=assessmentRequestSchema.parse(request);
 const {supabase,user}=await requireUser();const valuationDate=input.valuation_date??input.assessment_date;const priceMode=input.price_mode??'MANUAL';
 const {data:profile,error:pe}=await supabase.from('profiles').select('base_currency,zakat_method_id,nisab_standard').eq('id',user.id).single();if(pe)throw pe;const methodId=input.method_id??profile.zakat_method_id;if(!methodId)throw new Error('ZAKAT_METHOD_NOT_CONFIGURED');
 const {data:method,error:me}=await supabase.from('zakat_methods').select('*').eq('id',methodId).single();if(me)throw me;
 const {data:lots,error:le}=await supabase.from('lots').select('*,asset_accounts(id,name,asset_type,currency,is_zakatable,metadata,ownership_scope),transactions!lots_source_transaction_id_fkey(id,transaction_date)').eq('user_id',user.id);if(le)throw le;
 // Current residual lots cannot reconstruct a balance before a subsequent exit.
 const {data:futureExits,error:futureError}=await supabase.from('transactions').select('id').eq('user_id',user.id).gt('transaction_date',input.assessment_date).in('transaction_type',['SALE','WITHDRAWAL','TRANSFER_OUT','ZAKAT_PAYMENT','ADJUSTMENT','REVERSAL']).limit(1);
 if(futureError)throw futureError;if(futureExits?.length)throw new Error('HISTORICAL_BALANCE_RECONSTRUCTION_REQUIRED');
 const baseCurrency=profile.base_currency;const standard=input.nisab_standard??profile.nisab_standard??'SILVER';
 let priceQuery=supabase.from('market_prices').select('*').eq('valuation_date',valuationDate).in('asset_type',['GOLD','SILVER']).order('created_at',{ascending:false});if(input.price_source)priceQuery=priceQuery.eq('source',input.price_source);let {data:prices}=await priceQuery;
 if(priceMode==='REFERENCE'&&(!(prices??[]).length)){const refs=await fetchReferenceMetalPrices(valuationDate);if(refs.length){const {error:priceInsertError}=await supabase.from('market_prices').insert(refs.map(x=>({asset_type:x.metal,instrument_code:x.metal==='GOLD'?'XAU':'XAG',price_per_unit:x.pricePerGram,currency:x.currency,valuation_date:x.valuationDate,source:x.source})));if(priceInsertError)throw priceInsertError;let refreshed=supabase.from('market_prices').select('*').eq('valuation_date',valuationDate).in('asset_type',['GOLD','SILVER']).order('created_at',{ascending:false});if(input.price_source)refreshed=refreshed.eq('source',input.price_source);prices=(await refreshed).data;}}
 const metalPrices:Record<string,FrozenMetalPrice>={};
 for(const metal of ['GOLD','SILVER']){
  const ref=(prices??[]).find((p:any)=>p.asset_type===metal&&(p.karat==null||Number(p.karat)===(metal==='GOLD'?24:999)));
  const price=priceMode==='REFERENCE'?Number(ref?.price_per_unit??0):Number(metal==='GOLD'?input.gold_price??0:input.silver_price??0);
  const currency=priceMode==='REFERENCE'?(ref?.currency??baseCurrency):(input.price_currency??baseCurrency);
  if(currency!==baseCurrency&&(!input.fx_rate||input.price_currency!==currency))throw new Error('VALUATION_FX_RATE_REQUIRED');
  metalPrices[metal]={price,currency,fxRate:currency===baseCurrency?1:input.fx_rate!,source:priceMode==='REFERENCE'?(ref?.source??'market_prices'):'USER_MANUAL',priceId:priceMode==='REFERENCE'?ref?.id??null:null};
 }
 const goldPrice=metalPrices.GOLD.price,silverPrice=metalPrices.SILVER.price;
 const nisabValue=nisabFromPrice(standard,metalPrices);
 const zakatableLots=(lots??[]).filter((l:any)=>l.asset_accounts?.is_zakatable===true&&l.asset_accounts?.ownership_scope!=='ORGANIZATION'&&Number(l.remaining_quantity)>0&&l.acquisition_date<=input.assessment_date);
 const valuation=(l:any)=>frozenLotValuation(l,lots??[],baseCurrency,metalPrices);
 const marketValue=(l:any)=>valuation(l).marketValueBase;
 const poolValue=zakatableLots.reduce((s:any,l:any)=>s.add(marketValue(l)),new Decimal(0));
 let {data:cycle,error:cycleError}=await supabase.from('zakat_hawl_cycles').select('*').eq('user_id',user.id).in('status',['OPEN','ACTIVE']).order('cycle_no',{ascending:false}).limit(1).maybeSingle();if(cycleError)throw cycleError;
 if(!cycle&&poolValue.gte(nisabValue)){const startMethod=input.nisab_start_method??'MANUAL';const start=startMethod==='HISTORICAL_RECORDED'?historicalNisabDate(zakatableLots,nisabValue,input.assessment_date):input.nisab_reached_date;if(!start)throw new Error(startMethod==='HISTORICAL_RECORDED'?'HISTORICAL_NISAB_DATE_NOT_DERIVABLE':'PORTFOLIO_NISAB_DATE_REQUIRED');if(start>input.assessment_date)throw new Error('NISAB_DATE_AFTER_ASSESSMENT');const due=calculateHawl(method.calendar_type==='GREGORIAN'?'GREGORIAN':'HIJRI_TABULAR',new Date(start+'T00:00:00Z'),new Date(start+'T00:00:00Z')).dueDate.toISOString().slice(0,10);const {data:last}=await supabase.from('zakat_hawl_cycles').select('cycle_no').eq('user_id',user.id).order('cycle_no',{ascending:false}).limit(1).maybeSingle();const ins=await supabase.from('zakat_hawl_cycles').insert({user_id:user.id,cycle_no:Number(last?.cycle_no||0)+1,nisab_standard:standard,nisab_value_base:nisabValue.toString(),nisab_reached_date:start,hawl_start_date:start,hawl_due_date:due,status:'ACTIVE',price_mode:priceMode,price_source:priceMode==='REFERENCE'?(input.price_source??prices?.[0]?.source??'market_prices'):'USER_MANUAL',gold_price:goldPrice||null,silver_price:silverPrice||null,snapshot:{cycle_anchor_source:startMethod==='HISTORICAL_RECORDED'?'HISTORICAL_RECORDED_ACQUISITION_VALUES':'USER_CONFIRMED_PORTFOLIO_NISAB_DATE',historical_derivation:startMethod==='HISTORICAL_RECORDED'?{basis:'recorded original lot values accumulated by acquisition date',threshold:nisabValue.toString()}:null}}).select().single();if(ins.error)throw ins.error;cycle=ins.data;}
 const candidates=zakatableLots.filter((lot:any)=>!!lot.hawl_start_date).map((lot:any)=>{
  const account=lot.asset_accounts;const v=valuation(lot);
  const hawl=calculateHawl(method.calendar_type==='GREGORIAN'?'GREGORIAN':'HIJRI_TABULAR',new Date(lot.hawl_start_date+'T00:00:00Z'),new Date(input.assessment_date+'T00:00:00Z'));
  const due=hawl.dueDate.toISOString().slice(0,10);
  return {lotId:lot.id,assetName:account?.name,assetType:account?.asset_type,...v,hawlCompleted:hawl.completed,quantity:lot.remaining_quantity,
   hawlStartDate:lot.hawl_start_date,hawlDueDate:due,valuationSnapshot:{...v.valuationSnapshot,hawlDueDate:due,valuationDate}};
 }).filter((x:any)=>x.marketValueBase.gt(0));
 const calc=calculateAssessment(candidates,nisabValue,method.zakat_rate);const snapshot={schemaVersion:2,priceCurrency:input.price_currency??baseCurrency,baseCurrency,metalPrices,revisionOf:revisionOf??null,assessmentDate:input.assessment_date,valuationDate,methodCode:method.code,methodVersion:method.version,calendarType:method.calendar_type,nisabStandard:standard,nisabValue:nisabValue.toString(),portfolioMarketValue:poolValue.toString(),priceMode,priceSource:priceMode==='REFERENCE'?(input.price_source??prices?.[0]?.source??'market_prices'):'USER_MANUAL',prices:{gold:goldPrice,silver:silverPrice},fxRate:input.fx_rate??1,candidateLots:candidates.length,valuationSources:Array.from(new Set(candidates.map((c:any)=>c.valuationSource))),hawlCycleId:cycle?.id??null,calculatedAt:new Date().toISOString()};
 const assessmentPayload={assessment_date:input.assessment_date,valuation_date:valuationDate,method_id:method.id,nisab_standard:standard,nisab_quantity:standard==='GOLD'?85:595,nisab_value_base:nisabValue.toString(),total_zakatable_value:calc.totalEligibleValue.toString(),zakat_rate:method.zakat_rate,zakat_due:calc.zakatDue.toString(),currency:baseCurrency,status:'CALCULATED',method_version:method.version,calculation_snapshot:snapshot,hawl_cycle_id:cycle?.id??null,cycle_number:cycle?.cycle_no??null,assessment_kind:'RECALCULATION'};
 const lines=candidates.map((c:any,i:number)=>({lot_id:c.lotId,quantity:c.quantity,valuation_price:c.valuationPrice,valuation_currency:c.valuationCurrency,fx_rate:c.fxRate,valuation_snapshot:c.valuationSnapshot,market_value:c.marketValueBase.toString(),eligible_value:calc.lines[i].eligibleValue.toString(),zakat_amount:calc.lines[i].zakatAmount.toString(),eligibility_status:calc.lines[i].status,reason_code:calc.lines[i].status,explanation:`${c.assetName??'Asset'} → Lot ${c.lotId}: ${calc.lines[i].explanation}`}));
 const{data:assessment,error:saveError}=await supabase.rpc('save_zakat_assessment_snapshot',{p_assessment:assessmentPayload,p_lines:lines,p_revision_of:revisionOf??null});
 if(saveError)throw saveError;return{assessment,lines,cycle};
}
export async function confirmAssessment(id:string){const {supabase,user}=await requireUser();const {data,error}=await supabase.from('zakat_assessments').update({status:'CONFIRMED'}).eq('id',id).eq('user_id',user.id).eq('status','CALCULATED').select().single();if(error)throw error;await supabase.from('audit_logs').insert({user_id:user.id,entity_type:'zakat_assessment',entity_id:id,action:'CONFIRM',new_data:data});return data;}
