import Decimal from 'decimal.js';
import { requireUser } from './auth';
import { calculateAssessment } from '@/engine/assessment';
import { calculateHawl } from '@/engine/hawl';
import { fetchReferenceMetalPrices } from './reference-prices';

export async function listAssessments(){const {supabase,user}=await requireUser();const {data,error}=await supabase.from('zakat_assessments').select('*').eq('user_id',user.id).order('assessment_date',{ascending:false});if(error)throw error;return data;}
export type AssessmentRequest={assessment_date:string;valuation_date?:string;nisab_standard?:'GOLD'|'SILVER';method_id?:string;gold_price?:number;silver_price?:number;price_currency?:string;fx_rate?:number;price_mode?:'REFERENCE'|'MANUAL';price_source?:string;nisab_reached_date?:string};
export async function calculateAndSaveAssessment(input:AssessmentRequest){
 const {supabase,user}=await requireUser();const valuationDate=input.valuation_date??input.assessment_date;const priceMode=input.price_mode??'MANUAL';
 const {data:profile,error:pe}=await supabase.from('profiles').select('base_currency,zakat_method_id,nisab_standard').eq('id',user.id).single();if(pe)throw pe;const methodId=input.method_id??profile.zakat_method_id;if(!methodId)throw new Error('ZAKAT_METHOD_NOT_CONFIGURED');
 const {data:method,error:me}=await supabase.from('zakat_methods').select('*').eq('id',methodId).single();if(me)throw me;
 const {data:lots,error:le}=await supabase.from('lots').select('*,asset_accounts(name,asset_type,currency,is_zakatable,metadata),transactions!lots_source_transaction_id_fkey(id,transaction_date)').eq('user_id',user.id).gt('remaining_quantity',0);if(le)throw le;
 const baseCurrency=profile.base_currency;const standard=input.nisab_standard??profile.nisab_standard??'SILVER';
 let priceQuery=supabase.from('market_prices').select('*').eq('valuation_date',valuationDate).in('asset_type',['GOLD','SILVER']).order('created_at',{ascending:false});if(input.price_source)priceQuery=priceQuery.eq('source',input.price_source);let {data:prices}=await priceQuery;
 if(priceMode==='REFERENCE'&&(!(prices??[]).length)){const refs=await fetchReferenceMetalPrices(valuationDate);if(refs.length){const {error:priceInsertError}=await supabase.from('market_prices').insert(refs.map(x=>({asset_type:x.metal,instrument_code:x.metal==='GOLD'?'XAU':'XAG',price_per_unit:x.pricePerGram,currency:x.currency,valuation_date:x.valuationDate,source:x.source})));if(priceInsertError)throw priceInsertError;let refreshed=supabase.from('market_prices').select('*').eq('valuation_date',valuationDate).in('asset_type',['GOLD','SILVER']).order('created_at',{ascending:false});if(input.price_source)refreshed=refreshed.eq('source',input.price_source);prices=(await refreshed).data;}}
 const refGold=Number(prices?.find((p:any)=>p.asset_type==='GOLD')?.price_per_unit??0),refSilver=Number(prices?.find((p:any)=>p.asset_type==='SILVER')?.price_per_unit??0);const goldPrice=priceMode==='REFERENCE'?refGold:(input.gold_price??0),silverPrice=priceMode==='REFERENCE'?refSilver:(input.silver_price??0);if((standard==='GOLD'&&goldPrice<=0)||(standard==='SILVER'&&silverPrice<=0))throw new Error(priceMode==='REFERENCE'?'REFERENCE_PRICE_NOT_FOUND':'NISAB_PRICE_REQUIRED');const nisabValue=new Decimal(standard==='GOLD'?85:595).mul(standard==='GOLD'?goldPrice:silverPrice);
 const zakatableLots=(lots??[]).filter((l:any)=>l.asset_accounts?.is_zakatable===true);
 const marketValue=(l:any)=>{const a=l.asset_accounts,m=a?.metadata??{},remaining=new Decimal(l.remaining_quantity||0),original=new Decimal(l.original_quantity||l.remaining_quantity||1),share=original.gt(0)?Decimal.min(1,remaining.div(original)):new Decimal(1);let v=new Decimal(m.market_value??m.estimated_value??l.remaining_value_base??0).mul(share);if(a?.asset_type==='CASH'||a?.asset_type==='BANK')v=new Decimal(l.remaining_value_base||m.market_value||m.estimated_value||0);if(a?.asset_type==='GOLD'&&goldPrice>0){const k=Number(m.karat??24),p=k>0&&k<=24?k/24:1;v=remaining.mul(goldPrice).mul(p).mul(input.fx_rate??1)}else if(a?.asset_type==='SILVER'&&silverPrice>0){const raw=Number(m.purity??m.karat??999),p0=raw>1?raw/1000:raw,p=p0>0&&p0<=1?p0:1;v=remaining.mul(silverPrice).mul(p).mul(input.fx_rate??1)}return v};
 const poolValue=zakatableLots.reduce((s:any,l:any)=>s.add(marketValue(l)),new Decimal(0));
 let {data:cycle}=await supabase.from('zakat_hawl_cycles').select('*').eq('user_id',user.id).in('status',['OPEN','ACTIVE']).order('cycle_no',{ascending:false}).limit(1).maybeSingle();
 if(!cycle&&poolValue.gte(nisabValue)){if(!input.nisab_reached_date)throw new Error('PORTFOLIO_NISAB_DATE_REQUIRED');const start=input.nisab_reached_date;if(start>input.assessment_date)throw new Error('NISAB_DATE_AFTER_ASSESSMENT');const due=calculateHawl(method.calendar_type==='GREGORIAN'?'GREGORIAN':'HIJRI_TABULAR',new Date(start+'T00:00:00Z'),new Date(start+'T00:00:00Z')).dueDate.toISOString().slice(0,10);const {data:last}=await supabase.from('zakat_hawl_cycles').select('cycle_no').eq('user_id',user.id).order('cycle_no',{ascending:false}).limit(1).maybeSingle();const ins=await supabase.from('zakat_hawl_cycles').insert({user_id:user.id,cycle_no:Number(last?.cycle_no||0)+1,nisab_standard:standard,nisab_value_base:nisabValue.toString(),nisab_reached_date:start,hawl_start_date:start,hawl_due_date:due,status:'ACTIVE',price_mode:priceMode,price_source:priceMode==='REFERENCE'?(input.price_source??prices?.[0]?.source??'market_prices'):'USER_MANUAL',gold_price:goldPrice||null,silver_price:silverPrice||null,snapshot:{cycle_anchor_source:'USER_CONFIRMED_PORTFOLIO_NISAB_DATE'}}).select().single();if(ins.error)throw ins.error;cycle=ins.data;}
 const candidates=zakatableLots.filter((lot:any)=>!!lot.hawl_start_date).map((lot:any)=>{const account=lot.asset_accounts;const value=marketValue(lot);let purity=new Decimal(1);if(account?.asset_type==='GOLD'){const karat=Number(account?.metadata?.karat??24);purity=new Decimal(karat>0&&karat<=24?karat/24:1)}else if(account?.asset_type==='SILVER'){const raw=Number(account?.metadata?.purity??account?.metadata?.karat??999),p=raw>1?raw/1000:raw;purity=new Decimal(p>0&&p<=1?p:1)}const hawl=calculateHawl(method.calendar_type==='GREGORIAN'?'GREGORIAN':'HIJRI_TABULAR',new Date(lot.hawl_start_date+'T00:00:00Z'),new Date(input.assessment_date+'T00:00:00Z'));return{lotId:lot.id,assetName:account?.name,assetType:account?.asset_type,marketValueBase:value,hawlCompleted:hawl.completed,quantity:lot.remaining_quantity,purity:purity.toString(),valuationPrice:account?.asset_type==='GOLD'?goldPrice:account?.asset_type==='SILVER'?silverPrice:null,valuationCurrency:baseCurrency,fxRate:input.fx_rate??1,hawlStartDate:lot.hawl_start_date,hawlDueDate:hawl.dueDate.toISOString().slice(0,10),valuationSource:account?.asset_type==='GOLD'||account?.asset_type==='SILVER'?(priceMode==='REFERENCE'?(input.price_source??prices?.[0]?.source??'market_prices'):'USER_MANUAL'):(account?.metadata?.market_price_source??'ASSET_CURRENT_MARKET_VALUE')}}).filter((x:any)=>x.marketValueBase.gt(0));
 const calc=calculateAssessment(candidates,nisabValue,method.zakat_rate);const snapshot={assessmentDate:input.assessment_date,valuationDate,methodCode:method.code,methodVersion:method.version,calendarType:method.calendar_type,nisabStandard:standard,nisabValue:nisabValue.toString(),portfolioMarketValue:poolValue.toString(),priceMode,priceSource:priceMode==='REFERENCE'?(input.price_source??prices?.[0]?.source??'market_prices'):'USER_MANUAL',prices:{gold:goldPrice,silver:silverPrice},fxRate:input.fx_rate??1,candidateLots:candidates.length,valuationSources:Array.from(new Set(candidates.map((c:any)=>c.valuationSource))),hawlCycleId:cycle?.id??null,calculatedAt:new Date().toISOString()};
 const previous=cycle?.id?await supabase.from('zakat_assessments').select('id').eq('user_id',user.id).eq('hawl_cycle_id',cycle.id).neq('status','CANCELLED').order('created_at',{ascending:false}).limit(1).maybeSingle():null;
 const {data:assessment,error:ae}=await supabase.from('zakat_assessments').insert({user_id:user.id,assessment_date:input.assessment_date,valuation_date:valuationDate,method_id:method.id,nisab_standard:standard,nisab_quantity:standard==='GOLD'?85:595,nisab_value_base:nisabValue.toString(),total_zakatable_value:calc.totalEligibleValue.toString(),zakat_rate:method.zakat_rate,zakat_due:calc.zakatDue.toString(),currency:baseCurrency,status:'CALCULATED',method_version:method.version,calculation_snapshot:snapshot,hawl_cycle_id:cycle?.id??null,cycle_number:cycle?.cycle_no??null,assessment_kind:'RECALCULATION'}).select().single();if(ae)throw ae;
 if(previous?.data?.id)await supabase.from('zakat_assessments').update({superseded_by:assessment.id}).eq('id',previous.data.id).eq('user_id',user.id);
 if(cycle?.id)await supabase.from('zakat_hawl_cycles').update({assessment_id:assessment.id,valuation_date:valuationDate,nisab_value_base:nisabValue.toString(),snapshot:{latestAssessmentId:assessment.id,latestAssessmentDate:input.assessment_date,portfolioMarketValue:poolValue.toString()}}).eq('id',cycle.id).eq('user_id',user.id);
 const lines=candidates.map((c:any,i:number)=>({assessment_id:assessment.id,lot_id:c.lotId,quantity:c.quantity,valuation_price:c.valuationPrice,valuation_currency:c.valuationCurrency,fx_rate:c.fxRate,market_value:c.marketValueBase.toString(),eligible_value:calc.lines[i].eligibleValue.toString(),zakat_amount:calc.lines[i].zakatAmount.toString(),eligibility_status:calc.lines[i].status,reason_code:calc.lines[i].status,explanation:`${c.assetName??'Asset'} → Lot ${c.lotId}: ${calc.lines[i].explanation}`}));if(lines.length){const {error:lineError}=await supabase.from('zakat_assessment_lines').insert(lines);if(lineError)throw lineError;}await supabase.from('audit_logs').insert({user_id:user.id,entity_type:'zakat_assessment',entity_id:assessment.id,action:'CREATE_CYCLE_SNAPSHOT',new_data:assessment});return{assessment,lines,cycle};
}
export async function confirmAssessment(id:string){const {supabase,user}=await requireUser();const {data,error}=await supabase.from('zakat_assessments').update({status:'CONFIRMED'}).eq('id',id).eq('user_id',user.id).eq('status','CALCULATED').select().single();if(error)throw error;await supabase.from('audit_logs').insert({user_id:user.id,entity_type:'zakat_assessment',entity_id:id,action:'CONFIRM',new_data:data});return data;}
