import {beforeEach,describe,expect,it,vi} from 'vitest';
const fixture=vi.hoisted(()=>({rpc:vi.fn(),from:vi.fn(),guard:vi.fn(),requireUser:vi.fn(),single:vi.fn(),eq:vi.fn()}));
vi.mock('./auth',()=>({requireUser:fixture.requireUser}));
vi.mock('./financial-budget',()=>({assertFinancialBudgetQA:fixture.guard}));
import {executeFinancialEventAction} from './financial-events';
const organization='11111111-1111-4111-8111-111111111111';
const event='22222222-2222-4222-8222-222222222222';
const user='33333333-3333-4333-8333-333333333333';
beforeEach(()=>{vi.clearAllMocks();fixture.requireUser.mockResolvedValue({user:{id:user},supabase:{rpc:fixture.rpc,from:fixture.from}});fixture.rpc.mockImplementation(async(name)=>({data:name==='has_organization_permission'?true:event,error:null}));const chain={select:vi.fn().mockReturnThis(),eq:fixture.eq,single:fixture.single};fixture.eq.mockReturnValue(chain);fixture.from.mockReturnValue(chain);fixture.single.mockResolvedValue({data:{event_type:'EXPENSE',source_module:'OPERATIONAL_CONSOLE',created_by:event},error:null});});
describe('Authenticated operational command routing',()=>{
 it('fails closed outside the configured QA environment',async()=>{fixture.guard.mockImplementationOnce(()=>{throw new Error('FINANCIAL_BUDGET_QA_ONLY');});await expect(executeFinancialEventAction({action:'APPROVE',organization_id:organization,event_id:event,note:''})).rejects.toThrow('FINANCIAL_BUDGET_QA_ONLY');expect(fixture.rpc).not.toHaveBeenCalled();});
 it('denies unauthorized organization scope before event lookup',async()=>{fixture.rpc.mockResolvedValue({data:false,error:null});await expect(executeFinancialEventAction({action:'APPROVE',organization_id:organization,event_id:event,note:''})).rejects.toThrow('FINANCIAL_CORE_VIEW_DENIED');expect(fixture.from).not.toHaveBeenCalled();});
 it('denies viewer mutation even if the client requests approval',async()=>{fixture.rpc.mockImplementation(async(name,args)=>({data:name==='has_organization_permission'&&args.p_permission==='financial_core.view',error:null}));await expect(executeFinancialEventAction({action:'APPROVE',organization_id:organization,event_id:event,note:''})).rejects.toThrow('FINANCIAL_CORE_APPROVE_DENIED');expect(fixture.rpc.mock.calls.some(([name])=>name==='approve_financial_event')).toBe(false);});
 it('denies self approval on the server',async()=>{fixture.single.mockResolvedValue({data:{created_by:user},error:null});await expect(executeFinancialEventAction({action:'APPROVE',organization_id:organization,event_id:event,note:''})).rejects.toThrow('CREATOR_CANNOT_APPROVE_OWN_EVENT');});
 it('scopes event identity to the requested organization',async()=>{fixture.single.mockResolvedValue({data:null,error:{message:'event not found'}});await expect(executeFinancialEventAction({action:'APPROVE',organization_id:organization,event_id:event,note:''})).rejects.toThrow('event not found');expect(fixture.eq).toHaveBeenCalledWith('organization_id',organization);expect(fixture.rpc.mock.calls.some(([name])=>name==='approve_financial_event')).toBe(false);});
 it('prevents generic recognition of settlement',async()=>{fixture.single.mockResolvedValue({data:{event_type:'SETTLEMENT',source_module:'OPERATIONAL_CONSOLE'},error:null});await expect(executeFinancialEventAction({action:'TRANSITION',organization_id:organization,event_id:event,status:'ACTUAL',note:''})).rejects.toThrow('DEDICATED_POST_ACTION_REQUIRED');});
 it('forwards payment exactly to the existing atomic RPC',async()=>{const allocations=[{obligation_id:organization,flow_id:event,amount:50,base_amount:50,flow_amount:50,flow_currency:'SAR',flow_exchange_rate:1}];await executeFinancialEventAction({action:'POST_SETTLEMENT',organization_id:organization,event_id:event,account_id:user,direction:'OUTFLOW',settlement_date:'2027-01-15',amount:50,currency:'SAR',exchange_rate:1,base_amount:50,allocations});expect(fixture.rpc).toHaveBeenCalledWith('post_financial_settlement',{p_financial_event_id:event,p_account_id:user,p_direction:'OUTFLOW',p_settlement_date:'2027-01-15',p_amount:50,p_currency:'SAR',p_exchange_rate:1,p_base_amount:50,p_allocations:allocations});});
});
