import { requireUser } from '@/services/auth';
export async function listOrganizations(){const {supabase}=await requireUser();const {data,error}=await supabase.from('organizations').select('id,name,owner_user_id,entity_type,base_currency,created_at,updated_at').order('created_at',{ascending:false});if(error)throw error;return data??[]}
export async function createOrganization(input:{name:string;entity_type?:string;base_currency?:string}){const {supabase,user}=await requireUser();const name=input.name.trim();if(!name)throw new Error('ORGANIZATION_NAME_REQUIRED');const {data,error}=await supabase.from('organizations').insert({owner_user_id:user.id,name,entity_type:input.entity_type??'FAMILY',base_currency:input.base_currency??'SAR'}).select().single();if(error)throw error;const m=await supabase.from('organization_members').insert({organization_id:data.id,user_id:user.id,role:'OWNER'});if(m.error)throw m.error;return data}
export async function updateOrganization(id:string,input:{name:string}){const {supabase,user}=await requireUser();const name=input.name.trim();if(!name)throw new Error('ORGANIZATION_NAME_REQUIRED');const {data:current,error:currentError}=await supabase.from('organizations').select('name').eq('id',id).single();if(currentError)throw currentError;const {data,error}=await supabase.from('organizations').update({name,updated_at:new Date().toISOString()}).eq('id',id).select().single();if(error)throw error;if(current?.name&&current.name!==name){const budgetUpdate=await supabase.from('budget_plans').update({organization_name:name}).eq('user_id',user.id).eq('organization_name',current.name);if(budgetUpdate.error)throw budgetUpdate.error}return data}
export async function listEntities(orgId:string){const {supabase}=await requireUser();const {data,error}=await supabase.from('organization_entities').select('*').eq('organization_id',orgId).order('created_at');if(error)throw error;return data??[]}
export async function createEntity(orgId:string,input:{name:string;entity_type?:string;base_currency?:string}){const {supabase}=await requireUser();const {data,error}=await supabase.from('organization_entities').insert({organization_id:orgId,name:input.name,entity_type:input.entity_type??'PERSON',base_currency:input.base_currency??'SAR'}).select().single();if(error)throw error;return data}
export type OrganizationCostCenter={id:string;organization_id:string;code:string;name:string;active:boolean;created_at:string;updated_at:string};
export async function listCostCenters(organizationId:string){const {supabase}=await requireUser();const {data,error}=await supabase.from('organization_cost_centers').select('*').eq('organization_id',organizationId).eq('active',true).order('name');if(error)throw error;return (data??[]) as OrganizationCostCenter[]}
export async function createCostCenter(input:{organization_id:string;code:string;name:string}){const {supabase}=await requireUser();const code=input.code.trim().toUpperCase(),name=input.name.trim();if(!code||!name)throw new Error('COST_CENTER_CODE_AND_NAME_REQUIRED');const {data,error}=await supabase.from('organization_cost_centers').insert({organization_id:input.organization_id,code,name}).select().single();if(error)throw error;return data as OrganizationCostCenter}
export async function updateCostCenter(id:string,input:{name:string}){const {supabase}=await requireUser();const name=input.name.trim();if(!name)throw new Error('COST_CENTER_NAME_REQUIRED');const {data,error}=await supabase.from('organization_cost_centers').update({name,updated_at:new Date().toISOString()}).eq('id',id).select().single();if(error)throw error;return data as OrganizationCostCenter}
export async function createInvitation(orgId:string,email:string,role:string){const {supabase}=await requireUser();const {data,error}=await supabase.from('organization_invitations').insert({organization_id:orgId,email,role}).select().single();if(error)throw error;return data}
export async function listInvitations(orgId:string){const {supabase}=await requireUser();const {data,error}=await supabase.from('organization_invitations').select('*').eq('organization_id',orgId).order('created_at',{ascending:false});if(error)throw error;return data??[]}
