import {paymentCycleAssessmentId,paymentCycleDue} from '@/lib/zakat-cycle-payment-basis';
import {requireUser} from './auth';
import {paymentSchema} from '@/lib/validation/schemas';
export async function listPaymentCycles(){const{supabase,user}=await requireUser();const{data,error}=await supabase.from('zakat_hawl_cycles').select('id,cycle_no,status,hawl_start_date,hawl_due_date,final_assessment_id,assessment_id,final_zakat_due,snapshot,notes').eq('user_id',user.id).order('cycle_no',{ascending:false});if(error)throw error;const assessmentIds=Array.from(new Set((data??[]).map((c:any)=>paymentCycleAssessmentId(c)).filter(Boolean)));const assessmentDue=new Map<string,number>();if(assessmentIds.length){const{data:assessments,error:assErr}=await supabase.from('zakat_assessments').select('id,zakat_due,status').eq('user_id',user.id).in('id',assessmentIds);if(assErr)throw assErr;for(const a of assessments??[])if(!['CANCELLED','DRAFT'].includes((a as any).status))assessmentDue.set((a as any).id,Number((a as any).zakat_due||0));}const{data:alloc,error:allocError}=await supabase.from('zakat_payment_allocations').select('hawl_cycle_id,allocated_amount').eq('user_id',user.id);if(allocError)throw allocError;return(data??[]).map((c:any)=>{const paid=(alloc??[]).filter((a:any)=>a.hawl_cycle_id===c.id).reduce((s:number,a:any)=>s+Number(a.allocated_amount||0),0),assessmentId=paymentCycleAssessmentId(c),due=paymentCycleDue(c,assessmentId?assessmentDue.get(assessmentId):undefined),historicalSettled=Boolean(c.snapshot?.historical_settled),requiresHistoricalAssessment=Boolean(c.snapshot?.requires_historical_assessment)&&!assessmentId;return{...c,display_zakat_due:due,final_zakat_due:due,is_finalized:Boolean(c.final_assessment_id),historical_settled:historicalSettled,requires_historical_assessment:requiresHistoricalAssessment,paid_amount:paid,remaining_amount:historicalSettled?0:Math.max(0,due-paid)}})}
export async function listPayments(){const{supabase,user}=await requireUser();const{data,error}=await supabase.from('zakat_payments').select('*').eq('user_id',user.id).order('payment_date',{ascending:false}).order('created_at',{ascending:false});if(error)throw error;const ids=(data??[]).map((x:any)=>x.id);if(!ids.length)return[];const{data:alloc,error:alErr}=await supabase.from('zakat_payment_allocations').select('payment_id,hawl_cycle_id,assessment_id,assessment_line_id,asset_account_id,allocated_amount,due_date,asset_accounts(name,asset_type)').eq('user_id',user.id).in('payment_id',ids).order('due_date',{ascending:true});if(alErr)throw alErr;const by=new Map<string,any[]>();for(const a of alloc??[]){const xs=by.get((a as any).payment_id)??[];xs.push(a);by.set((a as any).payment_id,xs)}return(data??[]).map((p:any)=>{const allocations=by.get(p.id)??[],allocated=allocations.reduce((s,x)=>s+Number(x.allocated_amount||0),0);return{...p,allocations,allocated_amount:allocated,unallocated_amount:Math.max(0,Number(p.base_amount||0)-allocated)}})}
async function writePayment(input:unknown,id:string|null=null,remove=false){
 const {supabase}=await requireUser();
 const payload=remove?{}:paymentSchema.parse(input);
 const {data,error}=await supabase.rpc('write_zakat_payment',{p_input:payload,p_payment_id:id,p_delete:remove});
 if(error)throw error;return data;
}
export async function createPayment(input:unknown){return writePayment(input)}
export async function updatePayment(input:unknown){const raw=input as any;if(!raw.id)throw new Error('PAYMENT_ID_REQUIRED');return writePayment(input,raw.id)}
export async function deletePayment(id:string){return writePayment({},id,true)}
