import { requireUser } from './auth';
import { transactionSchema } from '@/lib/validation/schemas';
export async function listTransactions(){const {supabase,user}=await requireUser();const {data,error}=await supabase.from('transactions').select('*,asset_accounts(name,asset_type)').eq('user_id',user.id).order('transaction_date',{ascending:false});if(error)throw error;return data;}
export async function createTransaction(input:unknown){const p=transactionSchema.parse(input);const {supabase,user}=await requireUser();if(['WITHDRAWAL','SALE','TRANSFER_OUT','ZAKAT_PAYMENT'].includes(p.transaction_type)){const {data,error}=await supabase.rpc('post_withdrawal',{p_user_id:user.id,p_asset_account_id:p.asset_account_id,p_date:p.transaction_date,p_quantity:p.quantity,p_value:p.gross_value,p_currency:p.currency,p_base_currency:p.base_currency,p_base_value:p.base_value,p_notes:p.notes??null,p_allocation_method:'FIFO',p_transaction_type:p.transaction_type});if(error)throw error;await supabase.from('audit_logs').insert({user_id:user.id,entity_type:'transaction',entity_id:data,action:'CREATE',new_data:{...p,id:data}});return data;}const {data,error}=await supabase.from('transactions').insert({...p,user_id:user.id,created_by:user.id}).select().single();if(error)throw error;
if(['OPENING_BALANCE','ADD','PURCHASE','TRANSFER_IN'].includes(p.transaction_type) && p.quantity>0){
 const {error:lotError}=await supabase.from('lots').insert({user_id:user.id,asset_account_id:p.asset_account_id,source_transaction_id:data.id,acquisition_date:p.transaction_date,original_quantity:p.quantity,remaining_quantity:p.quantity,original_value_base:p.base_value,remaining_value_base:p.base_value,status:'ACTIVE',metadata:{source:'transaction_engine'}});
 if(lotError){await supabase.from('transactions').delete().eq('id',data.id).eq('user_id',user.id);throw lotError;}
}
await supabase.from('audit_logs').insert({user_id:user.id,entity_type:'transaction',entity_id:data.id,action:'CREATE',new_data:data});return data;}
export async function reverseTransaction(id:string){const {supabase,user}=await requireUser();const {data,error}=await supabase.rpc('reverse_transaction',{p_user_id:user.id,p_transaction_id:id});if(error)throw error;await supabase.from('audit_logs').insert({user_id:user.id,entity_type:'transaction',entity_id:data,action:'REVERSAL',new_data:{reversal_transaction_id:data,original_transaction_id:id}});return data;}
