import {requireUser} from './auth';
export async function closeCycle(cycleId:string,assessmentId?:string){const{supabase,user}=await requireUser();const{data:cycle,error}=await supabase.from('zakat_hawl_cycles').select('*').eq('id',cycleId).eq('user_id',user.id).single();if(error)throw error;if(!['OPEN','ACTIVE'].includes(cycle.status))throw new Error('CYCLE_NOT_ACTIVE');const finalId=assessmentId||cycle.assessment_id;if(!finalId)throw new Error('FINAL_ASSESSMENT_REQUIRED');const{data:assessment,error:ae}=await supabase.from('zakat_assessments').select('id,zakat_due').eq('id',finalId).eq('user_id',user.id).eq('hawl_cycle_id',cycleId).single();if(ae)throw ae;const{error:ce}=await supabase.rpc('close_zakat_cycle',{p_cycle_id:cycleId,p_final_assessment_id:finalId});if(ce)throw ce;await supabase.from('audit_logs').insert({user_id:user.id,entity_type:'zakat_hawl_cycle',entity_id:cycleId,action:'CLOSE_CYCLE',new_data:{final_assessment_id:finalId,final_zakat_due:assessment.zakat_due}});return{cycle_id:cycleId,final_assessment_id:finalId,final_zakat_due:assessment.zakat_due}}
export async function startNextCycle(previousCycleId:string){const{supabase,user}=await requireUser();const{data:prev,error}=await supabase.from('zakat_hawl_cycles').select('*').eq('id',previousCycleId).eq('user_id',user.id).single();if(error)throw error;if(prev.status!=='CLOSED'&&prev.status!=='PAID')throw new Error('PREVIOUS_CYCLE_NOT_CLOSED');const{data:existing}=await supabase.from('zakat_hawl_cycles').select('id').eq('user_id',user.id).in('status',['OPEN','ACTIVE']).maybeSingle();if(existing)return existing;const start=prev.hawl_due_date||new Date().toISOString().slice(0,10),d=new Date(`${start}T00:00:00Z`);d.setUTCFullYear(d.getUTCFullYear()+1);const due=d.toISOString().slice(0,10);const{data,error:ie}=await supabase.from('zakat_hawl_cycles').insert({user_id:user.id,cycle_no:Number(prev.cycle_no||0)+1,nisab_standard:prev.nisab_standard,nisab_value_base:prev.nisab_value_base,nisab_reached_date:start,hawl_start_date:start,hawl_due_date:due,status:'ACTIVE',snapshot:{rolled_from_cycle_id:previousCycleId,previous_final_zakat_due:prev.final_zakat_due}}).select().single();if(ie)throw ie;await supabase.from('audit_logs').insert({user_id:user.id,entity_type:'zakat_hawl_cycle',entity_id:data.id,action:'START_NEXT_CYCLE',new_data:{previous_cycle_id:previousCycleId,cycle_no:data.cycle_no}});return data}

export async function markHistoricalCycleSettled(cycleId:string){
 const{supabase,user}=await requireUser();
 const{data:cycle,error}=await supabase.from('zakat_hawl_cycles').select('*').eq('id',cycleId).eq('user_id',user.id).single();if(error)throw error;
 if(['OPEN','ACTIVE'].includes(cycle.status))throw new Error('ACTIVE_CYCLE_CANNOT_BE_HISTORICALLY_SETTLED');
 const{count:payments,error:pe}=await supabase.from('zakat_payment_allocations').select('id',{count:'exact',head:true}).eq('user_id',user.id).eq('hawl_cycle_id',cycleId);if(pe)throw pe;
 if((payments||0)>0)throw new Error('CYCLE_HAS_RECORDED_PAYMENTS');
 const finalId=cycle.final_assessment_id||cycle.assessment_id||null;
 let due=Number(cycle.final_zakat_due||0);
 if(finalId&&!due){const{data:a}=await supabase.from('zakat_assessments').select('zakat_due').eq('id',finalId).eq('user_id',user.id).maybeSingle();due=Number(a?.zakat_due||0)}
 const oldSnapshot=cycle.snapshot&&typeof cycle.snapshot==='object'?cycle.snapshot:{};
 const settledAt=new Date().toISOString();
 const{data,error:ue}=await supabase.from('zakat_hawl_cycles').update({status:'PAID',closed_at:cycle.closed_at||settledAt,final_assessment_id:finalId,final_zakat_due:due,snapshot:{...oldSnapshot,historical_settled:true,historical_settled_at:settledAt,historical_settlement_source:'USER_CONFIRMED_PREEXISTING_SETTLEMENT'},notes:[cycle.notes,'Historically settled before ZakatFlow; no synthetic payment created.'].filter(Boolean).join('\n')}).eq('id',cycleId).eq('user_id',user.id).select().single();if(ue)throw ue;
 await supabase.from('audit_logs').insert({user_id:user.id,entity_type:'zakat_hawl_cycle',entity_id:cycleId,action:'MARK_HISTORICALLY_SETTLED',old_data:cycle,new_data:data});return data;
}
