'use client';
import {useEffect,useState} from 'react';
import {usePathname} from 'next/navigation';
const COLS=[['asset','الأصل','Asset'],['date','تاريخ الشراء','Purchase date'],['hawl','الحول','Hawl'],['cost','التكلفة','Cost'],['current','القيمة الحالية','Current value'],['due','الزكاة المستحقة','Zakat due'],['paid','المدفوعة','Paid'],['remaining','المتبقي','Remaining'],['action','الإجراء','Action']] as const;
type Size='compact'|'normal'|'wide';
export default function AssetTableTools({ar}:{ar:boolean}){const path=usePathname();const active=path?.includes('/assets');const[open,setOpen]=useState(false);const[size,setSize]=useState<Size>('normal');const[visible,setVisible]=useState<Record<string,boolean>>(()=>Object.fromEntries(COLS.map(c=>[c[0],true])));
useEffect(()=>{if(!active)return;try{const s=localStorage.getItem('zf_asset_table');if(s){const p=JSON.parse(s);if(p.size)setSize(p.size);if(p.visible)setVisible((v:any)=>({...v,...p.visible}))}}catch{}},[active]);
useEffect(()=>{if(!active)return;try{localStorage.setItem('zf_asset_table',JSON.stringify({size,visible}))}catch{};const tables=document.querySelectorAll<HTMLTableElement>('.asset-group table');tables.forEach(t=>{t.dataset.size=size;COLS.forEach((c,i)=>{const show=visible[c[0]]!==false;t.querySelectorAll<HTMLElement>(`tr > *:nth-child(${i+1})`).forEach(el=>el.style.display=show?'':'none')})})},[active,size,visible]);
if(!active)return null;const all=COLS.every(c=>visible[c[0]]!==false);return <><style>{`.asset-table-tools{max-width:1240px;margin:14px auto -10px;padding:0 22px;position:relative}.att-bar{display:flex;gap:8px;align-items:center;justify-content:flex-end;flex-wrap:wrap}.att-panel{position:absolute;z-index:25;top:46px;inset-inline-end:22px;width:min(430px,calc(100vw - 44px));background:#fff;border:1px solid var(--line);border-radius:14px;padding:15px;box-shadow:0 14px 35px #0f231e20}.att-panel h4{margin:0 0 11px}.att-cols{display:grid;grid-template-columns:1fr 1fr;gap:7px}.att-cols label{display:flex;align-items:center;gap:7px;padding:8px;border:1px solid var(--line);border-radius:8px;color:var(--ink)}.att-cols input{width:auto;margin:0}.att-sizes{display:flex;gap:6px;margin-bottom:12px}.att-sizes button{flex:1}.asset-group table[data-size=compact] th,.asset-group table[data-size=compact] td{padding:7px 8px;font-size:11px}.asset-group table[data-size=normal] th,.asset-group table[data-size=normal] td{padding:12px;font-size:13px}.asset-group table[data-size=wide] th,.asset-group table[data-size=wide] td{padding:17px 20px;font-size:14px}.asset-group{overflow-x:auto}.asset-group table th{resize:horizontal;overflow:auto;min-width:90px}.asset-group table th:first-child{min-width:180px}@media(max-width:600px){.att-cols{grid-template-columns:1fr}}`}</style><div className="asset-table-tools"><div className="att-bar"><button className="btn secondary" onClick={()=>setSize(size==='compact'?'normal':size==='normal'?'wide':'compact')}>↔ {ar?'حجم الخانات':'Cell size'}: {size==='compact'?(ar?'صغير':'Compact'):size==='wide'?(ar?'واسع':'Wide'):(ar?'متوسط':'Normal')}</button><button className="btn secondary" onClick={()=>setOpen(x=>!x)}>☷ {ar?'اختيار الأعمدة':'Choose columns'}</button></div>{open&&<div className="att-panel"><h4>{ar?'تخصيص جدول الأصول':'Customize asset table'}</h4><div className="att-sizes"><button className={`btn ${size==='compact'?'':'secondary'}`} onClick={()=>setSize('compact')}>{ar?'صغير':'Compact'}</button><button className={`btn ${size==='normal'?'':'secondary'}`} onClick={()=>setSize('normal')}>{ar?'متوسط':'Normal'}</button><button className={`btn ${size==='wide'?'':'secondary'}`} onClick={()=>setSize('wide')}>{ar?'واسع':'Wide'}</button></div><div className="att-cols">{COLS.map(c=><label key={c[0]}><input type="checkbox" checked={visible[c[0]]!==false} onChange={e=>setVisible(v=>({...v,[c[0]]:e.target.checked}))}/>{ar?c[1]:c[2]}</label>)}</div><div style={{display:'flex',gap:7,marginTop:12}}><button className="btn secondary" onClick={()=>setVisible(Object.fromEntries(COLS.map(c=>[c[0],!all])))}>{all?(ar?'إخفاء الكل':'Hide all'):(ar?'إظهار الكل':'Show all')}</button><button className="btn" onClick={()=>setOpen(false)}>{ar?'تم':'Done'}</button></div></div>}</div></>}
