'use client';
import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import type {BudgetPlan} from '@/lib/budget-planning';
import {buildBudgetMetrics,createDefaultBudgetPlan,MONTH_KEYS} from '@/lib/budget-planning';
const AR_MONTHS=['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'];
const CATEGORY_LABELS_AR={REVENUE:'الإيرادات',COGS:'تكلفة المبيعات',OPEX:'المصروفات التشغيلية',CAPEX:'الإنفاق الرأسمالي',FINANCING:'خدمة الدين',ZAKAT:'الزكاة'};
const CATEGORY_LABELS_EN={REVENUE:'Revenue',COGS:'Cost of Sales',OPEX:'Operating Expenses',CAPEX:'Capital Expenditure',FINANCING:'Debt Service',ZAKAT:'Zakat'};
const LINE_LABELS_EN:Record<string,string>={'الإيرادات التشغيلية':'Operating Revenue','إيرادات أخرى':'Other Revenue','تكلفة المبيعات':'Cost of Sales','الرواتب':'Salaries','الإيجار والخدمات':'Rent & Utilities','التسويق':'Marketing','المصاريف المهنية':'Professional Fees','التقنية':'Technology','الإنفاق الرأسمالي':'Capital Expenditure','خدمة الدين':'Debt Service','مخصص ومدفوعات الزكاة':'Zakat Provision & Payments'};
const lineLabel=(name:string,ar:boolean)=>ar?name:(LINE_LABELS_EN[name]??name);
const categoryLabel=(category:keyof typeof CATEGORY_LABELS_AR,ar:boolean)=>ar?CATEGORY_LABELS_AR[category]:CATEGORY_LABELS_EN[category];
const STATUS_LABELS={DRAFT:'مسودة',IN_REVIEW:'قيد المراجعة',APPROVED:'معتمدة',ARCHIVED:'مؤرشفة'};
const fmt=(value:number,currency='SAR')=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(value)+' '+currency;
const pct=(value:number)=>new Intl.NumberFormat('en-US',{style:'percent',maximumFractionDigits:1}).format(value);
const scenarioFactor=(scenario:BudgetPlan['scenario'],category:BudgetPlan['lines'][number]['category'])=>{
 if(scenario==='BASE')return 1;
 if(scenario==='DOWNSIDE')return category==='REVENUE'?0.90:(category==='COGS'||category==='OPEX'?1.05:1);
 return category==='REVENUE'?1.10:(category==='COGS'?1.04:category==='OPEX'?1.03:1);
};
type Tab='dashboard'|'monthly'|'five-year'|'variance'|'forecast'|'cash-flow';
export default function BudgetPlanningWorkspace({locale}:{locale:string}){
 const searchParams=useSearchParams();
 const ar=locale==='ar',[plan,setPlan]=useState<BudgetPlan>(()=>createDefaultBudgetPlan(new Date().getFullYear()+1)),[tab,setTab]=useState<Tab>('dashboard'),[message,setMessage]=useState(''),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;(async()=>{try{const response=await fetch('/api/budget-plans',{cache:'no-store'});if(!response.ok)throw new Error('LOAD_FAILED');const plans=await response.json();if(active&&Array.isArray(plans)&&plans[0]?.id){const detail=await fetch(`/api/budget-plans/${plans[0].id}`,{cache:'no-store'});if(!detail.ok)throw new Error('LOAD_FAILED');const saved=await detail.json();if(active)setPlan(saved)}}catch{if(active)setMessage(ar?'تعذر تحميل الخطط المحفوظة.':'Could not load saved plans.')}finally{if(active)setLoading(false)}})();return()=>{active=false}},[ar]);
 useEffect(()=>{const requested=searchParams.get('tab') as Tab|null;if(requested&&(['dashboard','monthly','five-year','variance','forecast','cash-flow'] as Tab[]).includes(requested))setTab(requested)},[searchParams]);
 const metrics=useMemo(()=>buildBudgetMetrics(plan),[plan]),months=ar?AR_MONTHS:[...MONTH_KEYS];
 const t={title:ar?'التخطيط المالي والموازنات':'Financial Planning & Budgeting',subtitle:ar?'تخطيط مالي متكامل للموازنة والتوقعات والسيولة والأداء.':'Integrated budgeting, forecasting, liquidity and performance planning.',dashboard:ar?'لوحة الموازنة':'Budget dashboard',monthly:ar?'الموازنة الشهرية':'Monthly budget',five:ar?'الخطة الخمسية':'Five-year plan',variance:ar?'الفعلي مقابل الموازنة':'Actual vs budget',forecast:ar?'التوقعات':'Forecast',cash:ar?'التدفقات النقدية':'Cash flow'};
 const tabs:Array<[Tab,string]>=[['dashboard',t.dashboard],['monthly',t.monthly],['five-year',t.five],['variance',t.variance],['forecast',t.forecast],['cash-flow',t.cash]];
 const updatePlan=<K extends keyof BudgetPlan>(key:K,value:BudgetPlan[K])=>setPlan(current=>({...current,[key]:value}));
 const applyScenario=(scenario:BudgetPlan['scenario'])=>setPlan(current=>{
  const previous=current.scenario;
  const lines=current.lines.map(line=>{
   const oldFactor=scenarioFactor(previous,line.category),newFactor=scenarioFactor(scenario,line.category),ratio=newFactor/oldFactor;
   return {...line,monthly_forecast:(line.monthly_forecast??line.monthly_budget).map(value=>Math.round(Number(value||0)*ratio))};
  });
  return {...current,scenario,lines};
 });
 const updateAssumption=(key:string,value:number)=>setPlan(current=>({...current,assumptions:{...current.assumptions,[key]:value}}));
 const regenerateForecast=()=>setPlan(current=>{const growth=Number(current.assumptions.revenue_growth??0),cogsRatio=Number(current.assumptions.cogs_ratio??0.35);return {...current,lines:current.lines.map(line=>{const factor=scenarioFactor(current.scenario,line.category);let values=line.monthly_budget.map((value,month)=>Number(value||0)*factor*Math.pow(1+growth,month/12));if(line.category==='COGS'){const revenue=current.lines.filter(x=>x.category==='REVENUE').map(x=>x.monthly_budget).reduce((acc,row)=>acc.map((v,i)=>v+Number(row[i]||0)),Array(12).fill(0));values=revenue.map((value,month)=>value*cogsRatio*factor*Math.pow(1+growth,month/12))}return {...line,monthly_forecast:values.map(Math.round)}})}}); 
 const updateCell=(lineIndex:number,field:'monthly_budget'|'monthly_actual'|'monthly_forecast',month:number,value:number)=>setPlan(current=>({...current,lines:current.lines.map((line,index)=>index===lineIndex?{...line,[field]:Array.from({length:12},(_,i)=>i===month?(Number(value)||0):Number((line[field]??line.monthly_budget)[i]??0))}:line)}));
 async function save(status?:'IN_REVIEW'|'APPROVED'){setSaving(true);setMessage('');try{const method=plan.id?'PUT':'POST',url=plan.id?`/api/budget-plans/${plan.id}`:'/api/budget-plans';const response=await fetch(url,{method,headers:{'content-type':'application/json'},body:JSON.stringify(plan)}),body=await response.json();if(!response.ok)throw new Error(body.error||'SAVE_FAILED');let saved=body as BudgetPlan;if(status&&saved.id){const statusResponse=await fetch(`/api/budget-plans/${saved.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status})});const statusBody=await statusResponse.json();if(!statusResponse.ok)throw new Error(statusBody.error||'STATUS_UPDATE_FAILED');saved=statusBody}setPlan(current=>({...current,...saved,lines:saved.lines??current.lines,status:status??saved.status}));setMessage(ar?'تم حفظ الخطة بنجاح.':'Plan saved successfully.')}catch(error){setMessage(ar?'تعذر الحفظ. تأكد من تطبيق ترحيل قاعدة البيانات وتسجيل الدخول.':`Save failed: ${error instanceof Error?error.message:'Unknown error'}`)}finally{setSaving(false)}}
 function exportExcel(){const headers=['Category','Line item',...months,'Annual'],rows=plan.lines.map(line=>[categoryLabel(line.category,ar),lineLabel(line.name,ar),...line.monthly_budget,line.monthly_budget.reduce((a,b)=>a+b,0)]),html=`<table><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr>${rows.map(row=>`<tr>${row.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</table>`;const blob=new Blob(['\ufeff',html],{type:'application/vnd.ms-excel'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`ZakatFlow-Budget-${plan.fiscal_year}.xls`;link.click();URL.revokeObjectURL(link.href)}
 const maxRevenue=Math.max(...metrics.monthly.map(month=>month.revenue),1),points=metrics.monthly.map((month,index)=>`${index*(100/11)},${100-(month.revenue/maxRevenue)*82}`).join(' '),actualRevenueVariance=metrics.revenueVariancePct,hasActuals=plan.lines.some(line=>line.monthly_actual.some(value=>Number(value)!==0)),dashboardCash=plan.scenario==='BASE'?metrics.endingCash:metrics.forecastEndingCash,dashboardCashBuffer=plan.scenario==='BASE'?metrics.minimumCashBuffer:metrics.forecastMinimumCashBuffer;
 return <main className="container budget-plan"><div className="page-head budget-page-head"><div><span className="budget-eyebrow">{ar?'إدارة الأداء المالي':'Financial performance'}</span><h1>{t.title}</h1><p className="muted">{t.subtitle}</p></div><div className="page-command"><button className="btn secondary" onClick={exportExcel}>{ar?'تصدير Excel':'Export Excel'}</button><button className="btn secondary" disabled={saving||loading} onClick={()=>save()}>{ar?'حفظ المسودة':'Save draft'}</button><button className="btn" disabled={saving||loading} onClick={()=>save('IN_REVIEW')}>{ar?'إرسال للاعتماد':'Submit for approval'}</button>{plan.id&&plan.status==='IN_REVIEW'&&<button className="btn" disabled={saving||loading} onClick={()=>save('APPROVED')}>{ar?'اعتماد الخطة':'Approve plan'}</button>}</div></div>
 {message&&<div className={message.includes('تم ')||message.includes('success')?'success':'notice'}>{message}</div>}
 <section className="budget-tabs">{tabs.map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</section>
 <section className="budget-filters card"><label>{ar?'المنشأة':'Organization'}<input value={plan.organization_name} onChange={e=>updatePlan('organization_name',e.target.value)}/></label><label>{ar?'مركز التكلفة':'Cost center'}<select value={plan.cost_center} onChange={e=>updatePlan('cost_center',e.target.value)}><option value="ALL">{ar?'الكل':'All'}</option><option value="HQ">{ar?'الإدارة العامة':'Head office'}</option><option value="OPERATIONS">{ar?'التشغيل':'Operations'}</option></select></label><label>{ar?'السنة المالية':'Fiscal year'}<input type="number" value={plan.fiscal_year} onChange={e=>updatePlan('fiscal_year',Number(e.target.value))}/></label><label>{ar?'السيناريو':'Scenario'}<select value={plan.scenario} onChange={e=>applyScenario(e.target.value as BudgetPlan['scenario'])}><option value="BASE">{ar?'الأساسي':'Base'}</option><option value="DOWNSIDE">{ar?'المتحفظ':'Downside'}</option><option value="UPSIDE">{ar?'المتفائل':'Upside'}</option></select></label><label>{ar?'العملة':'Currency'}<select value={plan.currency} onChange={e=>updatePlan('currency',e.target.value)}><option>SAR</option><option>USD</option><option>AED</option></select></label><div className="budget-status"><small>{ar?'الحالة':'Status'}</small><strong>{ar?STATUS_LABELS[plan.status]:plan.status}</strong></div></section>
 <section className="card budget-assumptions"><div className="budget-card-head"><div><small>{ar?'محركات الخطة':'Plan drivers'}</small><h3>{ar?'الافتراضات المالية':'Financial assumptions'}</h3></div><button className="btn secondary" onClick={regenerateForecast}>{ar?'تحديث التوقع':'Refresh forecast'}</button></div><div className="budget-filters"><label>{ar?'نمو الإيرادات السنوي':'Annual revenue growth'}<input type="number" step="0.001" value={Number(plan.assumptions.revenue_growth??0)} onChange={e=>updateAssumption('revenue_growth',Number(e.target.value))}/></label><label>{ar?'نسبة تكلفة المبيعات':'COGS ratio'}<input type="number" step="0.01" value={Number(plan.assumptions.cogs_ratio??0.35)} onChange={e=>updateAssumption('cogs_ratio',Number(e.target.value))}/></label><label>{ar?'معدل الزكاة':'Zakat rate'}<input type="number" step="0.001" value={Number(plan.assumptions.zakat_rate??0.025)} onChange={e=>updateAssumption('zakat_rate',Number(e.target.value))}/></label></div></section>
 {tab==='dashboard'&&<><section className="budget-kpis"><Kpi title={ar?'الإيرادات السنوية':'Annual revenue'} value={fmt(metrics.revenue,plan.currency)} delta={hasActuals?pct(actualRevenueVariance):(ar?'بانتظار الفعلي':'Awaiting actuals')} tone="green"/><Kpi title="EBITDA" value={fmt(metrics.ebitda,plan.currency)} delta={pct(metrics.ebitdaMargin)} tone="teal"/><Kpi title={ar?'هامش الربح':'Gross margin'} value={pct(metrics.grossMargin)} delta={ar?'هامش الموازنة':'Budget margin'} tone="mint"/><Kpi title={ar?'الإنفاق الرأسمالي':'Annual CAPEX'} value={fmt(metrics.capex,plan.currency)} delta={ar?'حسب الموازنة':'Budgeted'} tone="amber"/><Kpi title={ar?'الرصيد النقدي':'Closing cash'} value={fmt(dashboardCash,plan.currency)} delta={dashboardCashBuffer<0?(ar?'أقل من المستهدف':'Below target'):(ar?'ضمن المستهدف':'On target')} tone={dashboardCashBuffer<0?'red':'blue'}/></section>
 <section className="budget-dashboard-grid"><div className="card budget-chart-card"><div className="budget-card-head"><div><small>{ar?'الأداء الشهري':'Monthly performance'}</small><h3>{ar?'الإيرادات الشهرية':'Monthly revenue'}</h3></div><span className="pill">{plan.fiscal_year}</span></div><div className="line-chart"><svg viewBox="0 0 100 105" preserveAspectRatio="none"><polyline points={points}/></svg><div className="chart-months">{months.map(month=><span key={month}>{month.slice(0,3)}</span>)}</div></div></div><div className="card budget-chart-card"><div className="budget-card-head"><div><small>{ar?'المقارنة':'Comparison'}</small><h3>{t.variance}</h3></div></div><VarianceBars ar={ar} budget={metrics.revenue} actual={metrics.actualRevenue} forecast={metrics.forecastRevenue}/></div><div className="card budget-alerts"><div className="budget-card-head"><div><small>{ar?'متابعة فورية':'Live review'}</small><h3>{ar?'تنبيهات الإدارة':'Management alerts'}</h3></div></div><Alert warn={dashboardCashBuffer<0} title={ar?'السيولة':'Liquidity'} body={dashboardCashBuffer<0?(ar?`أقل من المستهدف بـ ${fmt(Math.abs(dashboardCashBuffer),plan.currency)}`:`Below target by ${fmt(Math.abs(dashboardCashBuffer),plan.currency)}`):(ar?'ضمن الحد المستهدف':'Within target')}/><Alert warn={metrics.forecastVariance<0} title={ar?'التوقع':'Forecast'} body={ar?`انحراف ${pct(metrics.forecastVariance)} عن الموازنة`:`${pct(metrics.forecastVariance)} variance`}/><Alert title={ar?'حالة الخطة':'Plan status'} body={ar?STATUS_LABELS[plan.status]:plan.status}/></div></section><FiveYear plan={plan} ar={ar}/></>}
 {tab==='monthly'&&<BudgetTable plan={plan} months={months} field="monthly_budget" ar={ar} onChange={updateCell}/>}
 {tab==='variance'&&<VarianceTable plan={plan} months={months} ar={ar} onChange={updateCell}/>}
 {tab==='forecast'&&<BudgetTable plan={plan} months={months} field="monthly_forecast" ar={ar} onChange={updateCell}/>}
 {tab==='cash-flow'&&<CashFlowTable plan={plan} months={months} ar={ar}/>}
 {tab==='five-year'&&<FiveYear plan={plan} ar={ar} detailed/>}</main>
}
function Kpi({title,value,delta,tone}:{title:string;value:string;delta:string;tone:string}){return <div className={`card budget-kpi tone-${tone}`}><div className="budget-kpi-icon">◫</div><small>{title}</small><strong>{value}</strong><span>{delta}</span></div>}
function Alert({title,body,warn=false}:{title:string;body:string;warn?:boolean}){return <div className={`budget-alert ${warn?'warn':''}`}><span>{warn?'!':'✓'}</span><div><strong>{title}</strong><p>{body}</p></div></div>}
function VarianceBars({ar,budget,actual,forecast}:{ar:boolean;budget:number;actual:number;forecast:number}){const max=Math.max(budget,actual,forecast,1);return <div className="variance-bars">{[[ar?'الموازنة':'Budget',budget,'budget'],[ar?'الفعلي':'Actual',actual,'actual'],[ar?'التوقع':'Forecast',forecast,'forecast']].map(([label,value,tone])=><div key={String(label)}><label><span>{label}</span><strong>{new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(Number(value))}</strong></label><i><b className={String(tone)} style={{width:`${Math.max(2,Number(value)/max*100)}%`}}/></i></div>)}</div>}
function BudgetTable({plan,months,field,ar,onChange}:{plan:BudgetPlan;months:string[];field:'monthly_budget'|'monthly_forecast';ar:boolean;onChange:(line:number,field:'monthly_budget'|'monthly_actual'|'monthly_forecast',month:number,value:number)=>void}){return <section className="card budget-table-card"><div className="budget-card-head"><div><small>{ar?'مدخلات قابلة للتعديل':'Editable inputs'}</small><h3>{field==='monthly_budget'?(ar?'تفاصيل الموازنة الشهرية':'Monthly budget details'):(ar?'التوقع الشهري المحدّث':'Monthly rolling forecast')}</h3></div></div><div className="budget-table-scroll"><table className="budget-sheet"><thead><tr><th>{ar?'البند':'Line item'}</th>{months.map(m=><th key={m}>{m}</th>)}<th>{ar?'الإجمالي':'Annual'}</th></tr></thead><tbody>{plan.lines.map((line,lineIndex)=><tr key={line.name}><th><span>{categoryLabel(line.category,ar)}</span>{lineLabel(line.name,ar)}</th>{months.map((_,month)=><td key={month}><input aria-label={`${line.name} ${months[month]}`} type="number" value={(line[field]??line.monthly_budget)[month]} onChange={e=>onChange(lineIndex,field,month,Number(e.target.value))}/></td>)}<td><strong>{new Intl.NumberFormat('en-US').format((line[field]??line.monthly_budget).reduce((a,b)=>a+b,0))}</strong></td></tr>)}</tbody></table></div></section>}
function VarianceTable({plan,months,ar,onChange}:{plan:BudgetPlan;months:string[];ar:boolean;onChange:(line:number,field:'monthly_budget'|'monthly_actual'|'monthly_forecast',month:number,value:number)=>void}){return <section className="card budget-table-card"><div className="budget-card-head"><div><small>{ar?'أدخل الفعلي شهريًا ثم احفظ الخطة':'Enter monthly actuals, then save the plan'}</small><h3>{ar?'الفعلي مقابل الموازنة':'Actual vs budget'}</h3></div></div><div className="budget-table-scroll"><table className="budget-sheet"><thead><tr><th>{ar?'البند':'Line item'}</th>{months.map(m=><th key={m}>{m}</th>)}<th>{ar?'الفعلي السنوي':'Annual actual'}</th><th>{ar?'الموازنة السنوية':'Annual budget'}</th><th>{ar?'الانحراف':'Variance'}</th></tr></thead><tbody>{plan.lines.map((line,lineIndex)=>{const budget=line.monthly_budget.reduce((a,b)=>a+b,0),actual=line.monthly_actual.reduce((a,b)=>a+b,0),variance=actual-budget;return <tr key={line.name}><th>{lineLabel(line.name,ar)}</th>{months.map((_,month)=><td key={month}><input aria-label={`${line.name} actual ${months[month]}`} type="number" value={line.monthly_actual[month]} onChange={e=>onChange(lineIndex,'monthly_actual',month,Number(e.target.value))}/></td>)}<td><strong>{fmt(actual,plan.currency)}</strong></td><td>{fmt(budget,plan.currency)}</td><td className={variance<0?'negative':'positive'}>{fmt(variance,plan.currency)} · {pct(budget?variance/budget:0)}</td></tr>})}</tbody></table></div></section>}
function CashFlowTable({plan,months,ar}:{plan:BudgetPlan;months:string[];ar:boolean}){const m=buildBudgetMetrics(plan),useForecast=plan.scenario!=='BASE',cashSeries=useForecast?m.forecastClosingCash:m.closingCash,opening=cashSeries.map((_,i)=>i===0?plan.opening_cash:cashSeries[i-1]);return <section className="card budget-table-card"><div className="budget-card-head"><div><small>{ar?(useForecast?'حركة السيولة المتوقعة حسب النشاط':'حركة السيولة حسب النشاط'):(useForecast?'Forecast liquidity by activity':'Liquidity movement by activity')}</small><h3>{ar?'خطة التدفقات النقدية':'Cash-flow plan'}</h3></div><span className="pill">{ar?'الحد الأدنى ': 'Minimum cash '}{fmt(plan.minimum_cash_target,plan.currency)}</span></div><div className="budget-table-scroll"><table className="budget-sheet compact"><thead><tr><th>{ar?'البند':'Metric'}</th>{months.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody><tr><th>{ar?'الرصيد الافتتاحي':'Opening cash'}</th>{opening.map((x,i)=><td key={i}>{fmt(x,plan.currency)}</td>)}</tr><tr><th>{ar?'التدفق التشغيلي':'Operating cash flow'}</th>{m.monthly.map((x,i)=><td key={i}>{fmt(x.revenue-x.cogs-x.opex,plan.currency)}</td>)}</tr><tr><th>{ar?'التدفق الاستثماري':'Investing cash flow'}</th>{m.monthly.map((x,i)=><td className={x.capex>0?'negative':''} key={i}>{fmt(-x.capex,plan.currency)}</td>)}</tr><tr><th>{ar?'التدفق التمويلي':'Financing cash flow'}</th>{m.monthly.map((x,i)=><td className={x.financing>0?'negative':''} key={i}>{fmt(-x.financing,plan.currency)}</td>)}</tr><tr><th>{ar?'مدفوعات الزكاة':'Zakat payments'}</th>{m.monthly.map((x,i)=><td className={x.zakat>0?'negative':''} key={i}>{fmt(-x.zakat,plan.currency)}</td>)}</tr><tr><th>{ar?'صافي التدفق':'Net cash flow'}</th>{m.monthly.map((x,i)=><td className={x.netCash<0?'negative':'positive'} key={i}>{fmt(x.netCash,plan.currency)}</td>)}</tr><tr className="total"><th>{ar?'الرصيد الختامي':'Closing cash'}</th>{cashSeries.map((x,i)=><td className={x<plan.minimum_cash_target?'negative':''} key={i}>{fmt(x,plan.currency)}</td>)}</tr><tr><th>{ar?'فائض / عجز السيولة':'Cash surplus / gap'}</th>{cashSeries.map((x,i)=>{const gap=x-plan.minimum_cash_target;return <td className={gap<0?'negative':'positive'} key={i}>{fmt(gap,plan.currency)}</td>})}</tr></tbody></table></div></section>}
function FiveYear({plan,ar,detailed=false}:{plan:BudgetPlan;ar:boolean;detailed?:boolean}){const base=buildBudgetMetrics(plan),growth=Number(plan.assumptions.revenue_growth??0.12),years=Array.from({length:5},(_,i)=>plan.fiscal_year+i),rows=years.map((year,i)=>({year,revenue:base.revenue*Math.pow(1+growth,i),ebitda:base.ebitda*Math.pow(1+growth+.02,i),cash:base.endingCash+base.netCash*(i?Array.from({length:i},(_,n)=>Math.pow(1+growth,n+1)).reduce((a,b)=>a+b,0):0)})),maxRevenue=Math.max(...rows.map(row=>Math.abs(row.revenue)),1);return <section className={`card five-year-card ${detailed?'detailed':''}`}><div className="budget-card-head"><div><small>{ar?'نظرة استراتيجية':'Strategic outlook'}</small><h3>{ar?'الخطة الخمسية':'Five-year plan'}</h3></div><span className="pill">{pct(growth)} {ar?'نمو مفترض':'assumed growth'}</span></div><div className="five-year-bars">{rows.map((row,i)=><div key={row.year}><span>{row.year}</span><i><b style={{height:`${Math.max(8,Math.abs(row.revenue)/maxRevenue*100)}%`}}/></i><strong>{new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(row.revenue)}</strong>{detailed&&<small>EBITDA {new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(row.ebitda)} · {ar?'نقد':'Cash'} {new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(row.cash)}</small>}</div>)}</div></section>}
