'use client';

import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import type {EventPermissions} from '@/lib/financial-event-command';

type Row=Record<string,any>;
type Workspace={permissions:EventPermissions;events:Row[];sources:Row[];invoices:Row[];organization_entities:Row[];organization_cost_centers:Row[];financial_classifications:Row[];liquidity_counterparties:Row[];liquidity_accounts:Row[]};
type Detail={event:Row;permissions:EventPermissions;allowedActions:string[];canSelfApprove:boolean;balances:Row[];flows:Row[];reconciliation:Row[];applications:Row[];settlements:Row[];financial_event_lines:Row[];financial_event_obligations:Row[];financial_event_approvals:Row[];financial_event_status_history:Row[];financial_event_links:Row[]};
async function api(query:string,body?:unknown){const response=await fetch(`/api/financial-events${query}`,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result.error??'REQUEST_FAILED');return result;}
const fields=(form:HTMLFormElement)=>Object.fromEntries(new FormData(form).entries()) as Record<string,string>;
const nullable=(value:string)=>value||null;
const number=(value:string)=>Number(value);
const date=()=>new Date().toISOString().slice(0,10);
const money=(value:unknown)=>value==null?'—':Number(value).toLocaleString('en-US',{maximumFractionDigits:4});

export default function FinancialEventOperationalPanel({locale}:{locale:string}){
 const ar=locale==='ar';const t=(arabic:string,english:string)=>ar?arabic:english;
 const[context,setContext]=useState<{userId:string;organizations:Row[];project:string}|null>(null);
 const[organization,setOrganization]=useState('');const[workspace,setWorkspace]=useState<Workspace|null>(null);
 const[eventId,setEventId]=useState('');const[detail,setDetail]=useState<Detail|null>(null);
 const[targetId,setTargetId]=useState('');const[target,setTarget]=useState<Detail|null>(null);
 const[busy,setBusy]=useState(false);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');
 const[key,setKey]=useState('');const[lastCommand,setLastCommand]=useState<unknown>(null);
 const generation=useRef(0);const selection=useRef({organization,eventId,targetId});selection.current={organization,eventId,targetId};
 useEffect(()=>{setKey(crypto.randomUUID());api('?action=context').then(setContext).catch(e=>setError(e.message));},[]);
 const reload=useCallback(async()=>{
  if(!organization)return;const version=++generation.current;setLoading(true);setError('');
  try{const w=await api(`?action=workspace&organization=${organization}`);const[d,s]=await Promise.all([eventId?api(`?action=detail&organization=${organization}&event=${eventId}`):null,targetId?api(`?action=detail&organization=${organization}&event=${targetId}`):null]);if(version!==generation.current)return;setWorkspace(w);setDetail(d);setTarget(s);}catch(e){if(version===generation.current){setWorkspace(null);setDetail(null);setTarget(null);setError(e instanceof Error?e.message:'LOAD_FAILED');}}finally{if(version===generation.current)setLoading(false);}
 },[organization,eventId,targetId]);
 useEffect(()=>{void reload();return()=>{generation.current++;};},[reload]);
 function changeOrganization(value:string){generation.current++;setWorkspace(null);setDetail(null);setTarget(null);setEventId('');setTargetId('');setOrganization(value);setError('');setMessage('');setLastCommand(null);setKey(crypto.randomUUID());}
 async function submit(command:unknown){
  if(busy)return;const original=selection.current;setBusy(true);setError('');setMessage('');setLastCommand(command);
  try{const response=await api('',command);if(selection.current.organization!==original.organization)return;setMessage(`${t('نجحت العملية','Operation succeeded')}: ${typeof response.result==='object'?JSON.stringify(response.result):response.result}`);const action=(command as {action?:string}).action;if((action==='CREATE'||action==='PREPARE_VAT')&&typeof response.result==='string'){setDetail(null);setEventId(response.result);}else await reload();}
  catch(e){if(selection.current.organization===original.organization)setError(e instanceof Error?e.message:'WRITE_FAILED');}finally{setBusy(false);}
 }
 const can=(permission:keyof EventPermissions)=>!!workspace?.permissions[permission];
 const blocked=busy||loading;
 function select(label:string,name:string,rows:Row[],required=false,display='name',defaultValue=''){return <label>{label}<select name={name} required={required} defaultValue={defaultValue}><option value="">{t('اختر','Choose')}</option>{rows.map(row=><option key={row.id} value={row.id}>{row[display]??row.id}</option>)}</select></label>;}
 function input(label:string,name:string,defaultValue='',type='text',required=true){return <label>{label}<input name={name} type={type} defaultValue={defaultValue} required={required} step={type==='number'?'any':undefined} min={type==='number'?'0.0001':undefined}/></label>;}
 function formSubmit(callback:(v:Record<string,string>)=>unknown){return(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();void submit(callback(fields(e.currentTarget)));};}
 function create(v:Record<string,string>){const settlement=v.event_type==='SETTLEMENT';return{action:'CREATE',payload:{organization_id:organization,entity_id:nullable(v.entity_id),counterparty_id:nullable(v.counterparty_id),event_type:v.event_type,source_module:'OPERATIONAL_CONSOLE',source_event_key:v.key,event_date:v.event_date,due_date:nullable(v.due_date),base_currency:v.base_currency,description:v.description,lines:[{line_number:1,description:v.description,classification_id:v.classification_id,cost_center_id:nullable(v.cost_center_id),amount:number(v.amount),currency:v.currency,exchange_rate:number(v.exchange_rate),base_amount:number(v.base_amount),cash_direction:settlement?v.direction:'NON_CASH',vat_treatment:'OUT_OF_SCOPE',vat_rate:0,vat_amount:0}],obligations:!settlement&&v.obligation_amount?[{obligation_key:'primary',obligation_type:v.event_type==='REVENUE'?'RECEIVABLE':'PAYABLE',settleable_amount:number(v.obligation_amount),currency:v.currency,exchange_rate:number(v.exchange_rate),base_currency:v.base_currency,settleable_base_amount:number(v.obligation_base_amount)}]:[]}};}
 const organizations=context?.organizations??[];
 const financialClasses=workspace?.financial_classifications??[];
 const title=t('العمليات المالية','Financial operations');
 return <main className="financial-events-console" dir={ar?'rtl':'ltr'} aria-busy={busy||loading}>
  <header><div><h1>{title}</h1><p>{t('المصدر، الاعتراف، الالتزام والتسوية','Source, recognition, obligation and settlement')}</p></div><a href={`/${locale}/budget-planning`}>{t('الموازنة','Budget')}</a></header>
  <p className="notice">Financial Core QA · <code>{context?.project??'wtzgzmcgcqouziqzsfnl'}</code> · {t('الاعتراف ≠ الدفع. القيم التشغيلية تأتي من Financial Core.','Recognition ≠ payment. Operational values come from Financial Core.')}</p>
  <div className="financial-events-toolbar"><label>{t('المؤسسة','Organization')}<select value={organization} disabled={busy} onChange={e=>changeOrganization(e.target.value)}><option value="">{t('اختر مؤسسة','Choose organization')}</option>{organizations.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label><button type="button" disabled={!organization||blocked} onClick={()=>void reload()}>{t('تحديث','Refresh')}</button></div>
  {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{loading&&<p role="status">{t('جارٍ التحميل…','Loading…')}</p>}
  {workspace&&<>
   <section><h2>A · {t('الحدث / المصدر','Event / Source')}</h2>
    <p>{t('استخدم شاشة الفواتير لإنشاء المصدر الضريبي؛ تجهيز الاعتراف لا يعيد حساب الضريبة. الأبعاد المدعومة هنا Entity وCost Center؛ Projects غير مفعلة في تكامل الموازنة.','Use the invoice screen to create a tax source; preparation does not recalculate VAT. Supported dimensions are Entity and Cost Center; budget project integration is not enabled.')}</p>
    <nav className="financial-events-toolbar"><a href={`/${locale}/organizations`}>{t('إدارة الكيانات','Manage entities')}</a><a href={`/${locale}/vat`}>{t('مصادر VAT','VAT sources')}</a><a href={`/${locale}/liquidity`}>{t('الحسابات النقدية','Cash accounts')}</a></nav>
    {can('financial_core.create')&&can('vat.view')&&<details><summary>{t('تجهيز اعتراف من مصدر VAT','Prepare recognition from VAT source')}</summary><form onSubmit={formSubmit(v=>({action:'PREPARE_VAT',organization_id:organization,source_table:v.source_table,source_id:v.source_id,entity_id:v.entity_id,due_date:v.due_date}))}><div className="financial-events-grid"><label>{t('نوع المصدر','Source table')}<select name="source_table"><option>vat_documents</option><option>vat_einvoices</option></select></label>{select(t('المصدر','Source'),'source_id',[...workspace.sources.map(s=>({...s,name:`${s.document_number} · ${s.document_type} · Net ${money(s.source_net_amount)} / VAT ${money(s.source_tax_amount)} / Gross ${money(s.source_gross_amount)} · Recoverable ${s.recoverable_percent}%`})),...workspace.invoices.map(s=>({...s,name:`${s.invoice_number} · ${s.status}`}))],true)}{select(t('الكيان','Entity'),'entity_id',workspace.organization_entities,true)}{input(t('تاريخ الاستحقاق','Due date'),'due_date',date(),'date')}</div><button disabled={blocked}>{t('تجهيز للموافقة','Prepare for approval')}</button></form></details>}
    {can('financial_core.create')&&<details><summary>{t('إنشاء حدث / حدث تسوية','Create event / settlement event')}</summary><button type="button" disabled={blocked} onClick={()=>setKey(crypto.randomUUID())}>{t('عملية جديدة — مفتاح جديد','New operation — new key')}</button><form key={`${organization}:${key}`} onSubmit={formSubmit(create)}><div className="financial-events-grid">
     <label>{t('نوع الحدث','Event type')}<select name="event_type"><option value="EXPENSE">EXPENSE</option><option value="REVENUE">REVENUE</option><option value="SETTLEMENT">SETTLEMENT</option></select></label>
     {select(t('الكيان','Entity'),'entity_id',workspace.organization_entities,true)}{select(t('مركز التكلفة','Cost center'),'cost_center_id',workspace.organization_cost_centers)}{select(t('الطرف المقابل','Counterparty'),'counterparty_id',workspace.liquidity_counterparties)}{select(t('التصنيف','Classification'),'classification_id',financialClasses,true)}
     {input(t('مفتاح المصدر الثابت','Stable source key'),'key',key)}{input(t('التاريخ','Event date'),'event_date',date(),'date')}{input(t('الاستحقاق','Due date'),'due_date','','date',false)}{input(t('الوصف / المرجع','Description / reference'),'description')}
     {input(t('العملة','Currency'),'currency','SAR')}{input(t('عملة الأساس','Base currency'),'base_currency','SAR')}{input(t('المبلغ','Amount'),'amount','','number')}{input(t('سعر الصرف','Exchange rate'),'exchange_rate','1','number')}{input(t('مبلغ الأساس المعتمد','Source base amount'),'base_amount','','number')}
     <label>{t('اتجاه التسوية','Settlement direction')}<select name="direction"><option>OUTFLOW</option><option>INFLOW</option></select></label>{input(t('إجمالي الالتزام — للأحداث غير النقدية','Gross obligation — non-cash events'),'obligation_amount','','number',false)}{input(t('الالتزام بعملة الأساس','Obligation base amount'),'obligation_base_amount','','number',false)}
    </div><p>{t('هذا النموذج Out of scope VAT فقط. استخدم VAT adapter للاعتراف بفواتير ضريبية. التسوية تستخدم PAYABLE/RECEIVABLE ولا تستخدم تصنيف مصروف أو ضريبة.','This form is out-of-scope VAT only. Use the VAT adapter for tax invoices. Settlement uses PAYABLE/RECEIVABLE, not an expense or tax classification.')}</p><button disabled={blocked}>{t('إنشاء DRAFT','Create DRAFT')}</button></form></details>}
    {can('organization.edit')&&<details><summary>{t('إضافة تصنيف مالي','Add financial classification')}</summary><form onSubmit={formSubmit(v=>({action:'CLASSIFICATION',organization_id:organization,code:v.code,name:v.name,classification_type:v.classification_type}))}><div className="financial-events-grid">{input(t('الرمز','Code'),'code')}{input(t('الاسم','Name'),'name')}<label>{t('النوع','Type')}<select name="classification_type">{['OPEX','REVENUE','TAX','PAYABLE','RECEIVABLE','CAPEX','ASSET','LIABILITY','FINANCING','INVESTMENT'].map(x=><option key={x}>{x}</option>)}</select></label></div><button disabled={blocked}>{t('إضافة','Add')}</button></form></details>}
   </section>
   <section><h2>B · {t('سير العمل','Workflow')}</h2>{!workspace.events.length?<p>{t('لا توجد أحداث مالية لهذه المؤسسة.','No financial events for this organization.')}</p>:<div className="financial-events-scroll"><table><thead><tr><th>{t('المرجع','Reference')}</th><th>{t('النوع','Type')}</th><th>{t('التاريخ','Date')}</th><th>{t('الحالة','Status')}</th><th>{t('التفاصيل','Details')}</th></tr></thead><tbody>{workspace.events.map(e=><tr key={e.id}><td>{e.description||e.source_event_key}</td><td>{e.event_type}</td><td>{e.event_date}</td><td>{e.status}</td><td><button disabled={blocked} aria-pressed={eventId===e.id} onClick={()=>{setDetail(null);setEventId(e.id);}}>{t('فتح','Open')}</button></td></tr>)}</tbody></table></div>}
    {detail&&<article><h3>{detail.event.status} · {detail.event.description}</h3><p><code>{detail.event.id}</code></p><p>{t('المنشئ','Creator')}: <code>{detail.event.created_by}</code></p>
     {detail.event.created_by===context?.userId&&detail.event.status==='COMMITTED'&&!detail.canSelfApprove&&<p className="notice">{t('سياسة الموافقات الحالية تتطلب موافقًا مخولًا آخر لهذا الحدث.','The current approval policy requires another authorized approver for this event.')}</p>}
     <div className="financial-events-toolbar">{detail.allowedActions.filter(a=>a!=='POST_SETTLEMENT').map(action=><button key={action} disabled={blocked} onClick={()=>void submit(action==='APPROVE'?{action,organization_id:organization,event_id:eventId,note:'Operational approval'}:action==='RECOGNIZE_VAT'?{action,organization_id:organization,event_id:eventId}:{action:'TRANSITION',organization_id:organization,event_id:eventId,status:action,note:'Operational workflow'})}>{action}</button>)}</div>
     {detail.allowedActions.includes('POST_SETTLEMENT')&&detail.financial_event_links.some(l=>l.link_type==='OTHER'&&l.target_module==='liquidity_flows'&&l.metadata?.purpose==='SETTLEMENT_INSTRUCTION')&&(()=>{const instruction=detail.financial_event_links.find(l=>l.link_type==='OTHER'&&l.target_module==='liquidity_flows'&&l.metadata?.purpose==='SETTLEMENT_INSTRUCTION');return <form onSubmit={formSubmit(v=>({action:'POST_SAVED_SETTLEMENT',organization_id:organization,event_id:eventId,account_id:v.account_id||undefined,settlement_date:v.settlement_date||undefined}))}><p className="notice">{t('تعليمات السداد محفوظة من شاشة السيولة. يمكنك تأكيد البنك أو تغييره قبل الترحيل النهائي.','Settlement instructions are saved from Cash Management. Confirm or change the bank before final posting.')}</p><div className="financial-events-grid">{select(t('الحساب البنكي الفعلي','Actual bank account'),'account_id',workspace.liquidity_accounts,true,'name',instruction?.metadata?.account_id??'')}<label>{t('تاريخ السداد الفعلي','Actual settlement date')}<input name="settlement_date" type="date" defaultValue={instruction?.metadata?.settlement_date??date()}/></label><label>{t('المبلغ','Amount')}<input value={`${money(instruction?.metadata?.amount)} ${instruction?.metadata?.currency??''}`} readOnly/></label></div><button disabled={blocked}>{t('تنفيذ السداد وترحيله','Post cash settlement')}</button></form>})()}
     <h4>{t('سطور المصدر — قراءة فقط','Source lines — read only')}</h4><div className="financial-events-scroll"><table><thead><tr><th>Classification</th><th>Amount</th><th>Base</th><th>Direction</th><th>VAT treatment</th><th>Source role</th></tr></thead><tbody>{detail.financial_event_lines.map(l=><tr key={l.id}><td>{financialClasses.find(c=>c.id===l.classification_id)?.name??l.classification_id}</td><td>{money(l.amount)} {l.currency}</td><td>{money(l.base_amount)}</td><td>{l.cash_direction}</td><td>{l.vat_treatment}</td><td>{l.metadata?.source_role??'—'}</td></tr>)}</tbody></table></div>
     <details><summary>{t('سجل الحالة والموافقة','Status and approval history')}</summary><ul>{detail.financial_event_status_history.map(h=><li key={h.id}>{h.from_status??'—'} → {h.to_status} · {h.changed_at??h.created_at} · {h.note??h.reason}</li>)}{detail.financial_event_approvals.map(a=><li key={`a-${a.id}`}>{a.decision} · {a.approver_id} · {a.decided_at}</li>)}</ul></details>
     {can('organization.edit')&&<details><summary>{t('توجيه الحدث للموازنة','Route event to budget dimensions')}</summary><p>{t('توجيه صريح عبر configure_financial_budget، مع الحفاظ على هوية المصدر.','Explicit routing through configure_financial_budget, preserving source identity.')}</p><form onSubmit={formSubmit(v=>({action:'ROUTE',organization_id:organization,event_id:eventId,entity_id:v.entity_id,cost_center_id:nullable(v.cost_center_id),key:`route:${eventId}:${v.entity_id}:${v.cost_center_id}`}))}><div className="financial-events-grid">{select(t('الكيان','Entity'),'entity_id',workspace.organization_entities,true,'name',detail.event.entity_id??'')}{select(t('مركز التكلفة','Cost center'),'cost_center_id',workspace.organization_cost_centers)}</div><button disabled={blocked}>{t('توجيه','Route')}</button></form></details>}
    </article>}
   </section>
   <section><h2>C · {t('الالتزام والتسوية','Obligation & Settlement')}</h2>
    {detail&&<><div className="financial-events-scroll"><table><thead><tr><th>Obligation</th><th>Gross</th><th>Settled</th><th>Outstanding</th></tr></thead><tbody>{detail.balances.map(b=><tr key={b.obligation_id}><td>{b.obligation_type} · {b.obligation_key}</td><td>{money(b.adjusted_settleable_base_amount)}</td><td>{money(b.applied_base_amount)}</td><td>{money(b.outstanding_base_amount)}</td></tr>)}</tbody></table></div>{detail.financial_event_obligations.length>0&&!detail.balances.length&&<p>{t('الالتزام موجود لكنه لم يصبح ACTUAL بعد.','The obligation exists but has not become ACTUAL yet.')}</p>}
     <h4>{t('التدفقات المتوقعة والمطابقة','Expected cash flows and reconciliation')}</h4><div className="financial-events-scroll"><table><thead><tr><th>Flow</th><th>Expected</th><th>Settled</th><th>Outstanding</th><th>Cash allocated</th><th>Status</th></tr></thead><tbody>{detail.reconciliation.map(r=><tr key={r.flow_id}><td><code>{r.flow_id}</code></td><td>{money(r.expected_amount)}</td><td>{money(r.settled_amount)}</td><td>{money(r.expected_outstanding)}</td><td>{money(r.net_actual_cash_allocated)}</td><td>{r.settlement_status}</td></tr>)}</tbody></table></div>
     {detail.settlements.map(s=><p key={s.id}>{s.status} · {money(s.amount)} {s.currency} · <code>{s.id}</code></p>)}
    </>}
    {detail?.allowedActions.includes('POST_SETTLEMENT')&&!detail.financial_event_links.some(l=>l.link_type==='OTHER'&&l.target_module==='liquidity_flows'&&l.metadata?.purpose==='SETTLEMENT_INSTRUCTION')&&<>
     <p>{t('اختر حدث الاعتراف المستحق لتخصيص هذا الدفع. لا ينشئ الدفع مصروفًا جديدًا.','Choose the recognized obligation to allocate this payment. Payment creates no new expense.')}</p>
     <label>{t('حدث الاعتراف المستهدف','Target recognition event')}<select value={targetId} disabled={blocked} onChange={e=>{setTarget(null);setTargetId(e.target.value);}}><option value="">{t('اختر','Choose')}</option>{workspace.events.filter(e=>e.status==='ACTUAL'&&['EXPENSE','REVENUE','PAYABLE','RECEIVABLE'].includes(e.event_type)).map(e=><option value={e.id} key={e.id}>{e.description} · {e.source_event_key}</option>)}</select></label>
     {target&&<form key={`${organization}:${eventId}:${targetId}`} onSubmit={formSubmit(v=>({action:'POST_SETTLEMENT',organization_id:organization,event_id:eventId,account_id:v.account_id,direction:v.direction,settlement_date:v.settlement_date,amount:number(v.amount),currency:v.currency,exchange_rate:number(v.exchange_rate),base_amount:number(v.base_amount),allocations:[{obligation_id:v.obligation_id,flow_id:v.flow_id,amount:number(v.amount),base_amount:number(v.base_amount),flow_amount:number(v.flow_amount),flow_currency:v.flow_currency,flow_exchange_rate:number(v.flow_exchange_rate)}]}))}><div className="financial-events-grid">
      {select(t('الالتزام','Obligation'),'obligation_id',target.balances.map(b=>({...b,id:b.obligation_id,name:`${b.obligation_key} · Outstanding ${money(b.outstanding_base_amount)}`})),true)}{select(t('التدفق المتوقع','Expected flow'),'flow_id',target.flows.map(f=>({...f,name:`${f.title} · ${money(f.amount)} ${f.currency}`})),true)}{select(t('الحساب النقدي','Cash account'),'account_id',workspace.liquidity_accounts,true)}
      <label>{t('الاتجاه','Direction')}<select name="direction" defaultValue={detail.financial_event_lines[0]?.cash_direction}><option>OUTFLOW</option><option>INFLOW</option></select></label>{input(t('تاريخ الدفع','Payment date'),'settlement_date',date(),'date')}{input(t('مبلغ الدفع','Payment amount'),'amount',String(detail.financial_event_lines[0]?.amount??''),'number')}{input(t('عملة الدفع','Payment currency'),'currency',detail.financial_event_lines[0]?.currency??'SAR')}{input(t('سعر الصرف','Exchange rate'),'exchange_rate',String(detail.financial_event_lines[0]?.exchange_rate??1),'number')}{input(t('مبلغ الأساس','Base amount'),'base_amount',String(detail.financial_event_lines[0]?.base_amount??''),'number')}{input(t('المبلغ المخصص بعملة التدفق','Allocated amount in flow currency'),'flow_amount','','number')}{input(t('عملة التدفق','Flow currency'),'flow_currency',target.flows[0]?.currency??'SAR')}{input(t('سعر صرف التدفق','Flow exchange rate'),'flow_exchange_rate','1','number')}
     </div><p>{t('يتحقق RPC من المبلغ والعملة والكيان والتخصيص ومنع زيادة الدفع، ثم يرحّل العملية ذريًا.','The RPC validates amount, currency, entity, allocation and overpayment, then posts atomically.')}</p><button disabled={blocked}>{t('ترحيل التسوية','Post settlement')}</button></form>}
    </>}
   </section>
   {lastCommand&&<details><summary>{t('إعادة إرسال آخر طلب بنفس المفتاح','Retry last request with the same key')}</summary><p>{t('لإعادة المحاولة بعد انقطاع الاتصال دون إنشاء عملية مكررة.','Retry after a connection interruption without creating a duplicate operation.')}</p><button disabled={blocked} onClick={()=>void submit(lastCommand)}>{t('إعادة المحاولة','Retry')}</button></details>}
  </>}
 </main>;
}
