'use client';
import {use,useEffect,useMemo,useState} from 'react';
type T='CASH'|'BANK'|'GOLD'|'SILVER'|'STOCK'|'INVENTORY'|'RECEIVABLE'|'REAL_ESTATE'|'OTHER';
const TYPES:Array<[T,string,string]>=[['CASH','نقد','Cash'],['BANK','حساب بنكي','Bank'],['GOLD','ذهب','Gold'],['SILVER','فضة','Silver'],['STOCK','أسهم','Stocks'],['INVENTORY','مخزون','Inventory'],['RECEIVABLE','ذمم مدينة','Receivable'],['REAL_ESTATE','عقار','Real estate'],['OTHER','أصل آخر','Other']];
const FX=3.75, empty:any={asset_type:'CASH',name:'',amount:'',quantity:'',purchase_price:'',market_price:'',karat:'24',purpose:'',purchase_date:'',is_zakatable:true};
const fmt=(n:any)=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0);
const days=(s?:string)=>s?Math.max(0,Math.floor((Date.now()-new Date(`${s}T00:00:00`).getTime())/86400000)):0;
const hawl=(s:string,ar:boolean)=>{if(!s)return'—';const d=days(s),c=Math.floor(d/354),e=d%354,r=354-e;return c?ar?`${c} حول مكتمل + ${e} يوم`:`${c} hawl + ${e} days`:ar?`${e} من 354 يوم — متبقي ${r}`:`${e}/354 days — ${r} left`};
export default function Assets({params}:{params:Promise<{locale:string}>}){const{locale}=use(params),ar=locale==='ar';const[rows,setRows]=useState<any[]>([]),[form,setForm]=useState<any>(empty),[edit,setEdit]=useState<string|null>(null),[saving,setSaving]=useState(false),[msg,setMsg]=useState(''),[usd,setUsd]=useState(false);const cur=usd?'USD':'SAR',cv=(n:any)=>usd?Number(n||0)/FX:Number(n||0);
 const load=async()=>{const r=await fetch('/api/assets');setRows(r.ok?await r.json():[])};useEffect(()=>{void load()},[]);const m=(r:any,k:string)=>Number(r?.metadata?.[k]||0),val=(r:any)=>m(r,'market_value')||m(r,'estimated_value')||m(r,'purchase_value')||m(r,'opening_value');const metal=form.asset_type==='GOLD'||form.asset_type==='SILVER', market=metal||form.asset_type==='STOCK', qty=market||form.asset_type==='INVENTORY';const pc=qty?(+form.quantity||0)*(+form.purchase_price||0):(+form.amount||0),mv=market?(+form.quantity||0)*(+form.market_price||0):pc;const groups=useMemo(()=>TYPES.map(([type])=>({type,rows:rows.filter(r=>r.asset_type===type)})).filter(g=>g.rows.length),[rows]);const total=rows.reduce((s,r)=>s+val(r),0),cost=rows.reduce((s,r)=>s+m(r,'purchase_value'),0),z=rows.filter(r=>r.is_zakatable),completed=z.filter(r=>days(r.metadata?.purchase_date)>=354),near=z.filter(r=>{const d=days(r.metadata?.purchase_date);return d>=324&&d<354});const label=(t:string)=>TYPES.find(x=>x[0]===t)?.[ar?1:2]||t;
 const editRow=(r:any)=>{const d=r.metadata||{};setEdit(r.id);setForm({asset_type:r.asset_type,name:r.name,amount:d.opening_value??'',quantity:d.quantity??'',purchase_price:d.purchase_price??'',market_price:d.market_price??'',karat:d.karat??24,purpose:d.purpose??'',purchase_date:d.purchase_date??'',is_zakatable:r.is_zakatable});scrollTo({top:0,behavior:'smooth'})};
 const save=async()=>{if(!form.name||!form.purchase_date){setMsg(ar?'أدخل الاسم وتاريخ الشراء':'Enter name and purchase date');return}setSaving(true);const metadata:any={purchase_value:pc,market_value:mv,estimated_value:mv,purchase_date:form.purchase_date};if(form.amount)metadata.opening_value=+form.amount;if(form.quantity)metadata.quantity=+form.quantity;if(form.purchase_price)metadata.purchase_price=+form.purchase_price;if(form.market_price)metadata.market_price=+form.market_price;if(metal)metadata.karat=+form.karat;if(form.purpose)metadata.purpose=form.purpose;const body={...(edit?{id:edit}:{}),asset_type:form.asset_type,name:form.name,currency:'SAR',unit:metal?'g':form.asset_type==='STOCK'?'share':'unit',is_zakatable:form.is_zakatable,metadata};const r=await fetch('/api/assets',{method:edit?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(r.ok){setForm(empty);setEdit(null);setMsg(ar?'تم الحفظ':'Saved');await load()}else setMsg(ar?'تعذر الحفظ':'Save failed');setSaving(false)};
 return <main className="container"><div className="page-head"><div><h1>{ar?'الأصول':'Assets'}</h1><p className="muted">{ar?'العملة الأساسية ريال سعودي — التحويل للدولار للعرض فقط بسعر 3.75':'Base currency SAR — USD is display-only at 3.75'}</p></div><div><button className={`btn ${usd?'secondary':''}`} onClick={()=>setUsd(false)}>SAR</button>{' '}<button className={`btn ${!usd?'secondary':''}`} onClick={()=>setUsd(true)}>USD</button></div></div>
 <section className="grid section"><K t={ar?'القيمة الحالية':'Current value'} v={`${fmt(cv(total))} ${cur}`}/><K t={ar?'تكلفة الشراء':'Purchase cost'} v={`${fmt(cv(cost))} ${cur}`}/><K t={ar?'الربح / الخسارة':'Gain / loss'} v={`${fmt(cv(total-cost))} ${cur}`}/><K t={ar?'عدد الأصول':'Assets'} v={`${rows.length}`}/><K t={ar?'خاضع للزكاة':'Zakatable'} v={`${z.length}`}/><K t={ar?'اكتمل حولها':'Hawl completed'} v={`${completed.length}`}/><K t={ar?'خلال 30 يوماً':'Within 30 days'} v={`${near.length}`}/></section>
 <section className="card section"><h3>{edit?(ar?'تعديل الأصل':'Edit asset'):(ar?'إضافة أصل':'Add asset')}</h3><div className="form-grid"><label>{ar?'نوع الأصل':'Type'}<select value={form.asset_type} onChange={e=>setForm({...form,asset_type:e.target.value,karat:e.target.value==='SILVER'?'999':'24'})}>{TYPES.map(([v,a,e])=><option key={v} value={v}>{ar?a:e}</option>)}</select></label><label>{ar?'اسم الأصل':'Name'}<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>{ar?'عملة التسجيل':'Entry currency'}<input value="SAR" disabled/></label><label>{ar?'تاريخ الشراء / التملك':'Purchase date'}<input type="date" value={form.purchase_date} onChange={e=>setForm({...form,purchase_date:e.target.value})}/></label>{qty?<><label>{metal?(ar?'الوزن بالغرام':'Weight g'):(ar?'الكمية':'Quantity')}<input type="number" step="0.001" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>{ar?'سعر الشراء':'Purchase price'}<input type="number" step="0.01" value={form.purchase_price} onChange={e=>setForm({...form,purchase_price:e.target.value})}/></label>{market&&<label>{ar?'سعر السوق':'Market price'}<input type="number" step="0.01" value={form.market_price} onChange={e=>setForm({...form,market_price:e.target.value})}/></label>}{metal&&<label>{ar?'العيار / النقاوة':'Karat / purity'}<input type="number" step="0.001" value={form.karat} onChange={e=>setForm({...form,karat:e.target.value})}/></label>}</>:<label>{ar?'القيمة / الرصيد':'Value / balance'}<input type="number" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label>}<label>{ar?'زكوي؟':'Zakatable?'}<select value={form.is_zakatable?'1':'0'} onChange={e=>setForm({...form,is_zakatable:e.target.value==='1'})}><option value="1">{ar?'نعم':'Yes'}</option><option value="0">{ar?'لا':'No'}</option></select></label></div><button className="btn" onClick={save} disabled={saving}>{saving?(ar?'جارٍ الحفظ…':'Saving…'):(edit?(ar?'حفظ التعديلات':'Save changes'):(ar?'حفظ الأصل':'Save asset'))}</button>{edit&&<button className="btn secondary" onClick={()=>{setEdit(null);setForm(empty)}}>{ar?'إلغاء':'Cancel'}</button>}{msg&&<p className="muted">{msg}</p>}</section>
 <section className="section"><h2>{ar?'تقرير الأصول':'Asset report'}</h2>{groups.map(g=>{const sub=g.rows.reduce((s,r)=>s+val(r),0);return <div className="card section" key={g.type}><div className="page-head"><h3>{label(g.type)} <span className="pill">{g.rows.length}</span></h3><strong>{ar?'المجموع الفرعي':'Subtotal'}: {fmt(cv(sub))} {cur}</strong></div><table className="table"><thead><tr><th>{ar?'الأصل':'Asset'}</th><th>{ar?'تاريخ الشراء':'Purchase date'}</th><th>{ar?'الحول':'Hawl'}</th><th>{ar?'تكلفة الشراء':'Cost'}</th><th>{ar?'القيمة الحالية':'Current'}</th><th>{ar?'الفرق':'Gain/Loss'}</th><th>{ar?'إجراء':'Action'}</th></tr></thead><tbody>{g.rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.metadata?.purchase_date||'—'}</td><td>{hawl(r.metadata?.purchase_date,ar)}</td><td>{fmt(cv(m(r,'purchase_value')))} {cur}</td><td>{fmt(cv(val(r)))} {cur}</td><td>{fmt(cv(val(r)-m(r,'purchase_value')))} {cur}</td><td><button className="btn secondary" onClick={()=>editRow(r)}>{ar?'تعديل':'Edit'}</button></td></tr>)}</tbody></table></div>})}</section><section className="card section"><h2>{ar?'الإجمالي الكلي':'Grand total'}</h2><div className="metric">{fmt(cv(total))} {cur}</div><p className="muted">{ar?'الريال هو القيمة المحاسبية الأساسية؛ الدولار تحويل عرض فقط.':'SAR remains the accounting base; USD is display conversion only.'}</p></section></main>}
function K({t,v}:{t:string,v:string}){return <div className="card"><span className="muted">{t}</span><div className="metric">{v}</div></div>}
