'use client';

import { use, useEffect, useMemo, useState } from 'react';

type AssetType='CASH'|'BANK'|'GOLD'|'SILVER'|'STOCK'|'INVENTORY'|'RECEIVABLE'|'REAL_ESTATE'|'OTHER';
type FormState={asset_type:AssetType;name:string;currency:string;amount:string;quantity:string;purchase_price:string;market_price:string;karat:string;purpose:string;is_zakatable:boolean};
const TYPES:Array<[AssetType,string,string]>=[['CASH','نقد','Cash'],['BANK','حساب بنكي','Bank account'],['GOLD','ذهب','Gold'],['SILVER','فضة','Silver'],['STOCK','أسهم / محفظة','Stocks / portfolio'],['INVENTORY','مخزون تجاري','Inventory'],['RECEIVABLE','ذمم مدينة','Receivable'],['REAL_ESTATE','عقار','Real estate'],['OTHER','أصل آخر','Other']];
const CURRENCIES=['SAR','USD','EUR','AED','GBP','KWD','QAR','BHD','OMR','TRY','EGP','SYP','LBP'];

export default function Assets({params}:{params:Promise<{locale:string}>}){
 const {locale}=use(params); const ar=locale==='ar';
 const [rows,setRows]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [msg,setMsg]=useState('');
 const [form,setForm]=useState<FormState>({asset_type:'CASH',name:'',currency:'SAR',amount:'',quantity:'',purchase_price:'',market_price:'',karat:'24',purpose:'',is_zakatable:true});
 const load=async()=>{setLoading(true);const r=await fetch('/api/assets');const d=r.ok?await r.json():[];setRows(Array.isArray(d)?d:[]);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const metal=form.asset_type==='GOLD'||form.asset_type==='SILVER';
 const marketAsset=metal||form.asset_type==='STOCK';
 const valuedQuantity=marketAsset||form.asset_type==='INVENTORY';
 const purchaseValue=useMemo(()=>valuedQuantity?(Number(form.quantity)||0)*(Number(form.purchase_price)||0):(Number(form.amount)||0),[form,valuedQuantity]);
 const marketValue=useMemo(()=>marketAsset?(Number(form.quantity)||0)*(Number(form.market_price)||0):purchaseValue,[form,marketAsset,purchaseValue]);
 const gain=marketValue-purchaseValue;
 function changeType(asset_type:AssetType){setForm(f=>({...f,asset_type,name:'',amount:'',quantity:'',purchase_price:'',market_price:'',karat:asset_type==='SILVER'?'999':'24',purpose:''}));setMsg('')}
 async function save(){if(!form.name.trim()){setMsg(ar?'أدخل اسم الأصل.':'Enter an asset name.');return}setSaving(true);setMsg('');const metadata:any={purchase_value:purchaseValue,market_value:marketValue,estimated_value:marketValue};if(form.amount)metadata.opening_value=Number(form.amount);if(form.quantity)metadata.quantity=Number(form.quantity);if(form.purchase_price)metadata.purchase_price=Number(form.purchase_price);if(form.market_price)metadata.market_price=Number(form.market_price);if(metal&&form.karat)metadata.karat=Number(form.karat);if(form.purpose)metadata.purpose=form.purpose;metadata.market_price_source=marketAsset?'MANUAL':null;
 const r=await fetch('/api/assets',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({asset_type:form.asset_type,name:form.name.trim(),currency:form.currency,unit:metal?'g':form.asset_type==='STOCK'?'share':'unit',is_zakatable:form.is_zakatable,metadata})});const d=await r.json().catch(()=>({}));if(r.ok){setMsg(ar?'تم حفظ الأصل بنجاح.':'Asset saved successfully.');setForm(f=>({...f,name:'',amount:'',quantity:'',purchase_price:'',market_price:'',purpose:''}));await load()}else setMsg(d.error||(ar?'تعذر حفظ الأصل.':'Could not save asset.'));setSaving(false)}
 const label=(t:string)=>TYPES.find(x=>x[0]===t)?.[ar?1:2]||t; const m=(r:any,k:string)=>Number(r?.metadata?.[k]??0);
 return <main className="container"><div className="page-head"><div><h1>{ar?'الأصول':'Assets'}</h1><p className="muted">{ar?'سجّل تكلفة الشراء والقيمة السوقية الحالية لمتابعة الوعاء الزكوي والقيمة العادلة.':'Track acquisition cost and current market value for zakat and fair-value reporting.'}</p></div></div>
 <section className="card section"><h3>{ar?'إضافة أصل':'Add asset'}</h3><div className="form-grid">
 <label>{ar?'نوع الأصل':'Asset type'}<select value={form.asset_type} onChange={e=>changeType(e.target.value as AssetType)}>{TYPES.map(([v,a,e])=><option key={v} value={v}>{ar?a:e}</option>)}</select></label>
 <label>{ar?'اسم الأصل':'Asset name'}<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder={ar?(form.asset_type==='STOCK'?'مثال: سهم الراجحي':metal?'مثال: سبيكة 100 غرام':'مثال: الحساب الرئيسي'):'e.g. Main account'}/></label>
 <label>{ar?'العملة':'Currency'}<select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}>{CURRENCIES.map(c=><option key={c}>{c}</option>)}</select></label>
 {valuedQuantity?<><label>{metal?(ar?'الوزن بالغرام':'Weight (g)'):(ar?'الكمية':'Quantity')}<input type="number" min="0" step="any" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>{metal?(ar?'سعر الشراء للغرام':'Purchase price / g'):(ar?'سعر الشراء للوحدة':'Purchase price / unit')}<input type="number" min="0" step="any" value={form.purchase_price} onChange={e=>setForm({...form,purchase_price:e.target.value})}/></label>{marketAsset&&<label>{metal?(ar?'سعر السوق للغرام':'Market price / g'):(ar?'سعر السوق للسهم':'Market price / share')}<input type="number" min="0" step="any" value={form.market_price} onChange={e=>setForm({...form,market_price:e.target.value})}/>{marketAsset&&<small className="muted">{ar?'حالياً يدوي — الربط المباشر قيد الإضافة':'Manual for now — live feed integration next'}</small>}</label>}{metal&&<label>{form.asset_type==='GOLD'?(ar?'العيار':'Karat'):(ar?'النقاوة':'Purity')}<input type="number" min="0" step="any" value={form.karat} onChange={e=>setForm({...form,karat:e.target.value})}/></label>}</>:<label>{ar?'القيمة / الرصيد':'Value / balance'}<input type="number" min="0" step="any" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label>}
 {form.asset_type==='REAL_ESTATE'&&<label>{ar?'الغرض من العقار':'Property purpose'}<select value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})}><option value="">—</option><option value="TRADE">{ar?'للتجارة / البيع':'For trade / sale'}</option><option value="RENT">{ar?'للتأجير':'Rental'}</option><option value="PERSONAL">{ar?'استخدام شخصي':'Personal use'}</option></select></label>}
 <label>{ar?'المعاملة الزكوية':'Zakat treatment'}<select value={form.is_zakatable?'yes':'no'} onChange={e=>setForm({...form,is_zakatable:e.target.value==='yes'})}><option value="yes">{ar?'خاضع للزكاة':'Zakatable'}</option><option value="no">{ar?'غير خاضع حالياً':'Not zakatable'}</option></select></label></div>
 {(purchaseValue>0||marketValue>0)&&<div className="grid section"><div><span className="muted">{ar?'تكلفة الشراء':'Purchase cost'}</span><div className="metric">{purchaseValue.toLocaleString()} {form.currency}</div></div>{marketAsset&&<><div><span className="muted">{ar?'القيمة السوقية':'Market value'}</span><div className="metric">{marketValue.toLocaleString()} {form.currency}</div></div><div><span className="muted">{ar?'فرق القيمة':'Value change'}</span><div className="metric">{gain.toLocaleString()} {form.currency}</div></div></>}</div>}
 <button className="btn" onClick={save} disabled={saving}>{saving?(ar?'جارٍ الحفظ…':'Saving…'):(ar?'حفظ الأصل':'Save asset')}</button>{msg&&<p className="muted">{msg}</p>}</section>
 <section className="card section"><h3>{ar?'قائمة الأصول':'Asset list'}</h3>{loading?<p className="muted">{ar?'جارٍ التحميل…':'Loading…'}</p>:rows.length===0?<p className="muted">{ar?'لا توجد أصول بعد.':'No assets yet.'}</p>:<table className="table"><thead><tr><th>{ar?'الاسم':'Name'}</th><th>{ar?'النوع':'Type'}</th><th>{ar?'العملة':'Currency'}</th><th>{ar?'تكلفة الشراء':'Purchase cost'}</th><th>{ar?'القيمة السوقية':'Market value'}</th><th>{ar?'زكوي؟':'Zakatable?'}</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{label(r.asset_type)}</td><td>{r.currency}</td><td>{m(r,'purchase_value')?m(r,'purchase_value').toLocaleString():'—'}</td><td>{m(r,'market_value')?m(r,'market_value').toLocaleString():(m(r,'estimated_value')?m(r,'estimated_value').toLocaleString():'—')}</td><td>{r.is_zakatable?(ar?'نعم':'Yes'):(ar?'لا':'No')}</td></tr>)}</tbody></table>}</section></main>
}
