'use client';
import {useEffect,useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import {supabaseBrowser} from '@/lib/supabase/browser';

export default function AccountPage(){
 const params=useParams(); const locale=String(params.locale||'ar'); const ar=locale==='ar'; const router=useRouter();
 const [email,setEmail]=useState(''); const [name,setName]=useState(''); const [currency,setCurrency]=useState('SAR'); const [language,setLanguage]=useState(locale); const [msg,setMsg]=useState(''); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const s=supabaseBrowser();const {data:{user}}=await s.auth.getUser();if(!user){router.replace(`/${locale}/login`);return;}setEmail(user.email||'');setName(String(user.user_metadata?.full_name||user.user_metadata?.name||''));setLoading(false)})()},[locale,router]);
 async function save(){const s=supabaseBrowser();setMsg('');const {error}=await s.auth.updateUser({data:{full_name:name,base_currency:currency,preferred_language:language}});setMsg(error?error.message:(ar?'تم حفظ إعدادات الحساب.':'Account settings saved.'));if(!error&&language!==locale)router.push(`/${language}/account`)}
 async function logout(){const s=supabaseBrowser();await s.auth.signOut();router.replace(`/${locale}/login`);router.refresh()}
 if(loading)return <main className="container"><p>{ar?'جاري تحميل الحساب...':'Loading account...'}</p></main>;
 return <main className="container" style={{maxWidth:760}}><div className="card hero"><h1>{ar?'حسابي':'My Account'}</h1><p className="muted">{ar?'إدارة بيانات المستخدم وتفضيلات ZakatFlow.':'Manage your user details and ZakatFlow preferences.'}</p></div><section className="card" style={{marginTop:16}}><label>{ar?'الاسم':'Name'}</label><input value={name} onChange={e=>setName(e.target.value)} style={{width:'100%',padding:12,margin:'6px 0 14px'}}/><label>{ar?'البريد الإلكتروني':'Email'}</label><input value={email} disabled style={{width:'100%',padding:12,margin:'6px 0 14px'}}/><label>{ar?'العملة الأساسية':'Base currency'}</label><select value={currency} onChange={e=>setCurrency(e.target.value)} style={{width:'100%',padding:12,margin:'6px 0 14px'}}><option value="SAR">SAR — {ar?'ريال سعودي':'Saudi Riyal'}</option><option value="USD">USD — {ar?'دولار أمريكي':'US Dollar'}</option></select><label>{ar?'اللغة':'Language'}</label><select value={language} onChange={e=>setLanguage(e.target.value)} style={{width:'100%',padding:12,margin:'6px 0 18px'}}><option value="ar">العربية</option><option value="en">English</option></select><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button className="btn" onClick={save}>{ar?'حفظ التغييرات':'Save changes'}</button><button className="btn" onClick={logout}>{ar?'تسجيل الخروج':'Sign out'}</button></div>{msg&&<p className="muted">{msg}</p>}</section><section className="card" style={{marginTop:16}}><strong>{ar?'خصوصية البيانات':'Data privacy'}</strong><p className="muted">{ar?'كل مستخدم يعمل ضمن حسابه وبياناته الخاصة. بيانات Obada Zakah التجريبية لا تُضاف تلقائياً إلى حسابات المستخدمين الجدد.':'Each user works within their own account and data. Obada Zakah demo data is not automatically added to new user accounts.'}</p></section></main>
}
