'use client';
import {use, useEffect, useState} from 'react';
import {supabaseBrowser} from '@/lib/supabase/browser';
import {getAuthCallbackUrl, getAuthOrigin, getRecoveryRedirectUrl} from '@/lib/auth/recovery-redirect';

type Provider='google'|'facebook'|'apple';
export default function Login({params}:{params:Promise<{locale:string}>}){
 const {locale}=use(params);const ar=locale==='ar';
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [msg,setMsg]=useState('');const [busy,setBusy]=useState('');
 const [showPassword,setShowPassword]=useState(false);const [forgot,setForgot]=useState(false);
 const [invite,setInvite]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);
 useEffect(()=>{const canonical=getAuthOrigin(location.origin);if(canonical!==location.origin){const current=new URL(location.href);const target=new URL(canonical);current.protocol=target.protocol;current.host=target.host;location.replace(current.toString());return}const query=new URLSearchParams(location.search);setInvite(query.get('invite'));setError(query.get('error'))},[]);
 const callback=()=>getAuthCallbackUrl(location.origin,locale,undefined,invite);
 const validEmail=()=>{if(!email.trim()||!/^\S+@\S+\.\S+$/.test(email.trim())){setMsg(ar?'أدخل بريدًا إلكترونيًا صحيحًا.':'Enter a valid email address.');return false}return true};
 const friendlyError=(value:string)=>{const text=value.toLowerCase();if(text.includes('invalid login credentials'))return ar?'البريد أو كلمة المرور غير صحيحة.':'Email or password is incorrect.';if(text.includes('email not confirmed'))return ar?'أكد بريدك الإلكتروني أولًا.':'Confirm your email address first.';if(text.includes('rate limit'))return ar?'تم إرسال طلبات كثيرة مؤخرًا. انتظر قليلًا ثم أعد المحاولة.':'Too many requests. Please wait and try again.';return ar?'تعذر إكمال العملية. حاول مرة أخرى.':'Unable to complete the request. Please try again.'};
 async function passwordLogin(){if(!validEmail()||!password){setMsg(ar?'أدخل كلمة المرور.':'Enter your password.');return}setBusy('password');setMsg('');const supabase=supabaseBrowser();const {error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(error){setBusy('');setMsg(friendlyError(error.message));return}if(invite){const {error:inviteError}=await supabase.rpc('accept_organization_invitation',{p_token:invite});if(inviteError){await supabase.auth.signOut();setBusy('');setError(inviteError.message.includes('EMAIL_MISMATCH')?'invite_email':'invite_invalid');return}}setBusy('');location.assign(`/${locale}/dashboard`)}
 async function sendMagicLink(){if(!validEmail())return;setBusy('magic');setMsg('');const {error}=await supabaseBrowser().auth.signInWithOtp({email:email.trim().toLowerCase(),options:{emailRedirectTo:callback(),shouldCreateUser:true}});setBusy('');setMsg(error?friendlyError(error.message):(ar?'تم إرسال رابط الدخول إلى بريدك.':'A sign-in link was sent to your email.'))}
 async function sendReset(){if(!validEmail())return;setBusy('reset');setMsg('');const {error}=await supabaseBrowser().auth.resetPasswordForEmail(email.trim().toLowerCase(),{redirectTo:`${location.origin}/auth/reset-password`});setBusy('');setMsg(error?friendlyError(error.message):(ar?'تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك.':'A password reset link was sent to your email.'))}
 async function social(provider:Provider){setBusy(provider);setMsg('');const {error}=await supabaseBrowser().auth.signInWithOAuth({provider,options:{redirectTo:callback()}});if(error){setBusy('');setMsg(friendlyError(error.message))}}
 return <main className="container" style={{maxWidth:560,paddingTop:40,paddingBottom:60}}><div className="card hero"><div style={{textAlign:'center',marginBottom:22}}><span className="pill">ZakatFlow</span><h1>{invite?(ar?'قبول دعوة الشركة':'Accept organization invitation'):(ar?'تسجيل الدخول أو إنشاء حساب':'Sign in or create account')}</h1><p className="muted">{invite?(ar?'سجّل الدخول بالبريد المدعو نفسه لربط حسابك بالجهة والدور المحدد.':'Sign in with the invited email to link your account and role.'):(ar?'ابدأ حسابك خلال ثوانٍ. بيانات كل مستخدم مستقلة ومحمية.':'Start in seconds. Each user has an isolated, protected account.')}</p></div>
 <div style={{display:'grid',gap:10}}><button className="btn secondary" onClick={()=>social('google')} disabled={!!busy}>{busy==='google'?'…':(ar?'المتابعة باستخدام Google':'Continue with Google')}</button><button className="btn secondary" onClick={()=>social('apple')} disabled={!!busy}>{busy==='apple'?'…':(ar?'المتابعة باستخدام Apple':'Continue with Apple')}</button><button className="btn secondary" onClick={()=>social('facebook')} disabled={!!busy}>{busy==='facebook'?'…':(ar?'المتابعة باستخدام Facebook':'Continue with Facebook')}</button></div>
 <div style={{display:'flex',alignItems:'center',gap:12,margin:'22px 0'}}><div style={{height:1,background:'var(--border,#ddd)',flex:1}}/><span className="muted">{ar?'أو':'OR'}</span><div style={{height:1,background:'var(--border,#ddd)',flex:1}}/></div>
 <label>{ar?'البريد الإلكتروني':'Email address'}<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="email@example.com" style={{width:'100%',padding:12,margin:'8px 0 12px'}}/></label>
 {!forgot&&<><label>{ar?'كلمة المرور':'Password'}<span style={{display:'flex',gap:8,marginTop:8}}><input type={showPassword?'text':'password'} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void passwordLogin()}} style={{width:'100%',padding:12}}/><button type="button" className="btn secondary" onClick={()=>setShowPassword(v=>!v)}>{showPassword?(ar?'إخفاء':'Hide'):(ar?'إظهار':'Show')}</button></span></label><button className="btn" style={{width:'100%',marginTop:12}} onClick={passwordLogin} disabled={!!busy}>{busy==='password'?(ar?'جارٍ الدخول…':'Signing in…'):(ar?'تسجيل الدخول':'Sign in')}</button><button type="button" className="btn secondary" style={{width:'100%'}} onClick={sendMagicLink} disabled={!!busy}>{busy==='magic'?(ar?'جارٍ الإرسال…':'Sending…'):(ar?'الدخول عبر رابط البريد':'Sign in with Magic Link')}</button><button type="button" className="btn secondary" style={{width:'100%'}} onClick={()=>{setForgot(true);setMsg('')}} disabled={!!busy}>{ar?'نسيت كلمة المرور؟':'Forgot password?'}</button></>}
 {forgot&&<><button className="btn" style={{width:'100%',marginTop:4}} onClick={sendReset} disabled={!!busy}>{busy==='reset'?(ar?'جارٍ الإرسال…':'Sending…'):(ar?'إرسال رابط الاستعادة':'Send reset link')}</button><button type="button" className="btn secondary" style={{width:'100%'}} onClick={()=>{setForgot(false);setMsg('')}}>{ar?'العودة لتسجيل الدخول':'Back to sign in'}</button></>}
 {error&&<p className="muted" role="alert" style={{marginTop:14,color:'#b42318'}}>{error==='invite_email'?(ar?'رابط الدعوة مخصص لبريد آخر. سجّل بالبريد الذي استقبل الدعوة.':'This invitation belongs to another email. Sign in with the invited address.'):error==='invite_invalid'?(ar?'الدعوة غير صالحة أو انتهت صلاحيتها. اطلب من مسؤول الجهة إرسال دعوة جديدة.':'This invitation is invalid or expired. Ask an organization admin to send a new one.'):ar?'تعذر تسجيل الدخول. أعد المحاولة.':'Sign-in failed. Please try again.'}</p>}{msg&&<p className="muted" role="status" style={{marginTop:14}}>{msg}</p>}<p className="muted" style={{fontSize:13,marginTop:20,textAlign:'center'}}>{ar?'بالمتابعة فإنك تستخدم حساباً شخصياً مستقلاً داخل ZakatFlow.':'By continuing, you use an independent personal ZakatFlow account.'}</p></div></main>
}
