'use client';
import {use, useState} from 'react';
import {supabaseBrowser} from '@/lib/supabase/browser';

type Provider='google'|'facebook'|'apple';
export default function Login({params}:{params:Promise<{locale:string}>}){
 const {locale}=use(params);const ar=locale==='ar';
 const [email,setEmail]=useState('');const [msg,setMsg]=useState('');const [busy,setBusy]=useState('');
 const callback=()=>`${location.origin}/auth/callback?next=/${locale}/dashboard`;
 async function emailLogin(){if(!email.trim()){setMsg(ar?'أدخل بريدك الإلكتروني.':'Enter your email address.');return}setBusy('email');setMsg('');const supabase=supabaseBrowser();const {error}=await supabase.auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:callback(),shouldCreateUser:true}});setBusy('');setMsg(error?.message||(ar?'تم إرسال رابط آمن إلى بريدك. إذا كنت مستخدماً جديداً فسيتم إنشاء حسابك تلقائياً.':'A secure sign-in link was sent. A new account will be created automatically if needed.'))}
 async function social(provider:Provider){setBusy(provider);setMsg('');const supabase=supabaseBrowser();const {error}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo:callback()}});if(error){setBusy('');setMsg(error.message)}}
 return <main className="container" style={{maxWidth:560,paddingTop:40,paddingBottom:60}}><div className="card hero"><div style={{textAlign:'center',marginBottom:22}}><span className="pill">ZakatFlow</span><h1>{ar?'تسجيل الدخول أو إنشاء حساب':'Sign in or create account'}</h1><p className="muted">{ar?'ابدأ حسابك خلال ثوانٍ. بيانات كل مستخدم مستقلة ومحمية.':'Start in seconds. Each user has an isolated, protected account.'}</p></div>
 <div style={{display:'grid',gap:10}}><button className="btn secondary" onClick={()=>social('google')} disabled={!!busy}>{busy==='google'?'…':(ar?'المتابعة باستخدام Google':'Continue with Google')}</button><button className="btn secondary" onClick={()=>social('apple')} disabled={!!busy}>{busy==='apple'?'…':(ar?'المتابعة باستخدام Apple':'Continue with Apple')}</button><button className="btn secondary" onClick={()=>social('facebook')} disabled={!!busy}>{busy==='facebook'?'…':(ar?'المتابعة باستخدام Facebook':'Continue with Facebook')}</button></div>
 <div style={{display:'flex',alignItems:'center',gap:12,margin:'22px 0'}}><div style={{height:1,background:'var(--border,#ddd)',flex:1}}/><span className="muted">{ar?'أو':'OR'}</span><div style={{height:1,background:'var(--border,#ddd)',flex:1}}/></div>
 <label>{ar?'البريد الإلكتروني':'Email address'}<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void emailLogin()}} placeholder="email@example.com" style={{width:'100%',padding:12,margin:'8px 0 12px'}}/></label><button className="btn" style={{width:'100%'}} onClick={emailLogin} disabled={!!busy}>{busy==='email'?(ar?'جارٍ الإرسال…':'Sending…'):(ar?'المتابعة بالبريد الإلكتروني':'Continue with email')}</button>{msg&&<p className="muted" style={{marginTop:14}}>{msg}</p>}<p className="muted" style={{fontSize:13,marginTop:20,textAlign:'center'}}>{ar?'بالمتابعة فإنك تستخدم حساباً شخصياً مستقلاً داخل ZakatFlow.':'By continuing, you use an independent personal ZakatFlow account.'}</p></div></main>
}
