-- Full cash-flow accounting taxonomy: group -> detailed treatment -> Financial Core classification.
alter table public.liquidity_flow_categories add column if not exists accounting_group text, add column if not exists treatment_code text;
alter table public.liquidity_flow_categories drop constraint if exists liquidity_flow_categories_accounting_group_check;
alter table public.liquidity_flow_categories add constraint liquidity_flow_categories_accounting_group_check check (accounting_group is null or accounting_group in ('REVENUE','EXPENSE','PAYROLL','ASSETS','INVESTMENTS','FINANCING','EQUITY','CUSTOMERS','SUPPLIERS','TAX','ZAKAT','ADVANCES','TRANSFERS','OTHER'));
alter table public.liquidity_flow_categories drop constraint if exists liquidity_flow_categories_treatment_code_check;
alter table public.liquidity_flow_categories add constraint liquidity_flow_categories_treatment_code_check check (treatment_code is null or treatment_code in ('SALES_REVENUE','SERVICE_REVENUE','OTHER_REVENUE','ADMIN_EXPENSE','OPERATING_EXPENSE','SELLING_MARKETING_EXPENSE','FINANCE_COST','OTHER_EXPENSE','ADMIN_PAYROLL','OPERATING_PAYROLL','SALES_MARKETING_PAYROLL','FIXED_ASSET_PURCHASE','INTANGIBLE_ASSET_PURCHASE','CAPITAL_PROJECT','FINANCIAL_INVESTMENT','STRATEGIC_INVESTMENT','LOAN_PROCEEDS','DEBT_PRINCIPAL_PAYMENT','EQUITY_CONTRIBUTION','OWNER_DISTRIBUTION','CUSTOMER_INVOICE','CUSTOMER_COLLECTION','SUPPLIER_INVOICE','SUPPLIER_PAYMENT','VAT','OTHER_TAX','ZAKAT_ACCRUAL','ZAKAT_PAYMENT','CUSTOMER_ADVANCE','SUPPLIER_PREPAYMENT','BANK_TRANSFER','OTHER'));
update public.liquidity_flow_categories set accounting_group=coalesce(accounting_group,case flow_group when 'PAYROLL' then 'PAYROLL' when 'TAX' then 'TAX' when 'FINANCING' then 'FINANCING' when 'INVESTMENT' then 'INVESTMENTS' when 'OPERATING' then case when financial_classification_type='REVENUE' then 'REVENUE' else 'EXPENSE' end else 'OTHER' end),treatment_code=coalesce(treatment_code,case financial_classification_type when 'REVENUE' then 'OTHER_REVENUE' when 'OPEX' then 'OPERATING_EXPENSE' when 'CAPEX' then 'CAPITAL_PROJECT' when 'ASSET' then 'FIXED_ASSET_PURCHASE' when 'INVESTMENT' then 'FINANCIAL_INVESTMENT' when 'FINANCING' then 'LOAN_PROCEEDS' when 'EQUITY' then 'EQUITY_CONTRIBUTION' when 'TAX' then 'OTHER_TAX' when 'ZAKAT' then 'ZAKAT_ACCRUAL' when 'RECEIVABLE' then 'CUSTOMER_COLLECTION' when 'PAYABLE' then 'SUPPLIER_PAYMENT' when 'TRANSFER' then 'BANK_TRANSFER' else 'OTHER' end);
insert into public.liquidity_flow_categories(organization_id,code,name_ar,name_en,flow_group,accounting_group,treatment_code,allowed_direction,financial_classification_type,active,is_system,created_by)
select o.id,v.code,v.ar,v.en,v.fg,v.ag,v.tc,v.dir,v.fc,true,true,null from public.organizations o cross join (values
('SALES_REVENUE','إيرادات مبيعات','Sales revenue','OPERATING','REVENUE','SALES_REVENUE','INFLOW','REVENUE'),('SERVICE_REVENUE','إيرادات خدمات','Service revenue','OPERATING','REVENUE','SERVICE_REVENUE','INFLOW','REVENUE'),('OTHER_REVENUE','إيرادات أخرى','Other revenue','OPERATING','REVENUE','OTHER_REVENUE','INFLOW','REVENUE'),
('ADMIN_EXPENSE','مصروفات إدارية','Administrative expenses','OPERATING','EXPENSE','ADMIN_EXPENSE','OUTFLOW','OPEX'),('OPERATING_EXPENSE','مصروفات تشغيلية','Operating expenses','OPERATING','EXPENSE','OPERATING_EXPENSE','OUTFLOW','OPEX'),('SELLING_MARKETING_EXPENSE','مصروفات بيع وتسويق','Selling & marketing expenses','OPERATING','EXPENSE','SELLING_MARKETING_EXPENSE','OUTFLOW','OPEX'),('FINANCE_COST','فوائد ورسوم تمويل','Finance costs','FINANCING','EXPENSE','FINANCE_COST','OUTFLOW','OPEX'),
('ADMIN_PAYROLL','رواتب إدارية','Administrative payroll','PAYROLL','PAYROLL','ADMIN_PAYROLL','OUTFLOW','OPEX'),('OPERATING_PAYROLL','رواتب تشغيلية','Operating payroll','PAYROLL','PAYROLL','OPERATING_PAYROLL','OUTFLOW','OPEX'),('SALES_MARKETING_PAYROLL','رواتب مبيعات وتسويق','Sales & marketing payroll','PAYROLL','PAYROLL','SALES_MARKETING_PAYROLL','OUTFLOW','OPEX'),
('FIXED_ASSET_PURCHASE','شراء أصول ثابتة','Fixed asset purchase','INVESTMENT','ASSETS','FIXED_ASSET_PURCHASE','OUTFLOW','ASSET'),('INTANGIBLE_ASSET_PURCHASE','شراء أصول غير ملموسة','Intangible asset purchase','INVESTMENT','ASSETS','INTANGIBLE_ASSET_PURCHASE','OUTFLOW','ASSET'),('CAPITAL_PROJECT','مشروع رأسمالي / CAPEX','Capital project / CAPEX','INVESTMENT','ASSETS','CAPITAL_PROJECT','OUTFLOW','CAPEX'),('FINANCIAL_INVESTMENT','استثمار مالي','Financial investment','INVESTMENT','INVESTMENTS','FINANCIAL_INVESTMENT','OUTFLOW','INVESTMENT'),('STRATEGIC_INVESTMENT','استثمار استراتيجي','Strategic investment','INVESTMENT','INVESTMENTS','STRATEGIC_INVESTMENT','OUTFLOW','INVESTMENT'),
('LOAN_PROCEEDS','متحصلات قرض / تمويل','Loan proceeds','FINANCING','FINANCING','LOAN_PROCEEDS','INFLOW','FINANCING'),('DEBT_PRINCIPAL_PAYMENT','سداد أصل قرض','Debt principal repayment','FINANCING','FINANCING','DEBT_PRINCIPAL_PAYMENT','OUTFLOW','PAYABLE'),('EQUITY_CONTRIBUTION','مساهمة رأسمالية','Equity contribution','FINANCING','EQUITY','EQUITY_CONTRIBUTION','INFLOW','EQUITY'),('OWNER_DISTRIBUTION','توزيعات / مسحوبات ملاك','Owner distribution / drawings','FINANCING','EQUITY','OWNER_DISTRIBUTION','OUTFLOW','EQUITY'),
('CUSTOMER_INVOICE','فاتورة عميل','Customer invoice','OPERATING','CUSTOMERS','CUSTOMER_INVOICE','INFLOW','REVENUE'),('CUSTOMER_COLLECTION','تحصيل عميل','Customer collection','OPERATING','CUSTOMERS','CUSTOMER_COLLECTION','INFLOW','RECEIVABLE'),('SUPPLIER_INVOICE','فاتورة مورد','Supplier invoice','OPERATING','SUPPLIERS','SUPPLIER_INVOICE','OUTFLOW','OPEX'),('SUPPLIER_PAYMENT','سداد مورد','Supplier payment','OPERATING','SUPPLIERS','SUPPLIER_PAYMENT','OUTFLOW','PAYABLE'),
('VAT','ضريبة القيمة المضافة','VAT','TAX','TAX','VAT','BOTH','TAX'),('OTHER_TAX','ضرائب أخرى','Other taxes','TAX','TAX','OTHER_TAX','OUTFLOW','TAX'),('ZAKAT_ACCRUAL','استحقاق زكاة','Zakat accrual','TAX','ZAKAT','ZAKAT_ACCRUAL','OUTFLOW','ZAKAT'),('ZAKAT_PAYMENT','سداد زكاة مستحقة','Zakat payment','TAX','ZAKAT','ZAKAT_PAYMENT','OUTFLOW','PAYABLE'),('CUSTOMER_ADVANCE','دفعة مقدمة من عميل','Customer advance','OPERATING','ADVANCES','CUSTOMER_ADVANCE','INFLOW','LIABILITY'),('SUPPLIER_PREPAYMENT','دفعة مقدمة لمورد','Supplier prepayment','OPERATING','ADVANCES','SUPPLIER_PREPAYMENT','OUTFLOW','ASSET'),('BANK_TRANSFER','تحويل بين الحسابات','Bank transfer','OTHER','TRANSFERS','BANK_TRANSFER','BOTH','TRANSFER')
) v(code,ar,en,fg,ag,tc,dir,fc) where not exists(select 1 from public.liquidity_flow_categories c where c.organization_id=o.id and c.code=v.code);