import {NextResponse} from 'next/server';import Decimal from 'decimal.js';import {requireUser} from '@/services/auth';import {calculateAssessment} from '@/engine/assessment';import {calculateHawl} from '@/engine/hawl';
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){try{const{id}=await params;const{supabase,user}=await requireUser();const{data,error}=await supabase.from('zakat_assessments').select('*,zakat_methods(code,name_ar,name_en),zakat_assessment_lines(*)').eq('id',id).eq('user_id',user.id).single();if(error)throw error;return NextResponse.json(data)}catch(e:any){return NextResponse.json({error:e.message},{status:e.message==='UNAUTHORIZED'?401:404})}}
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){try{
 const{id}=await params;const{supabase,user}=await requireUser();const body=await req.json();
 const{data:old,error}=await supabase.from('zakat_assessments').select('*').eq('id',id).eq('user_id',user.id).single();if(error||!old)throw new Error('ASSESSMENT_NOT_FOUND');
 const{data:linkedCycle}=old.hawl_cycle_id?await supabase.from('zakat_hawl_cycles').select('id,status,assessment_id,final_assessment_id').eq('id',old.hawl_cycle_id).eq('user_id',user.id).maybeSingle():{data:null};
 if(linkedCycle&&['CLOSED','PAID'].includes(linkedCycle.status))return NextResponse.json({error:'CLOSED_CYCLE_ASSESSMENT_LOCKED'},{status:409});
 const assessmentDate=typeof body.assessment_date==='string'?body.assessment_date:old.assessment_date,valuationDate=typeof body.valuation_date==='string'?body.valuation_date:old.valuation_date,methodId=typeof body.method_id==='string'?body.method_id:old.method_id,standard=body.nisab_standard==='GOLD'||body.nisab_standard==='SILVER'?body.nisab_standard:old.nisab_standard;
 const{data:method,error:me}=await supabase.from('zakat_methods').select('*').eq('id',methodId).single();if(me)throw me;
 const oldSnap=old.calculation_snapshot||{},priceMode=body.price_mode==='MANUAL'||body.price_mode==='REFERENCE'?body.price_mode:(oldSnap.priceMode||'MANUAL'),goldPrice=Number(body.gold_price??oldSnap.prices?.gold??0),silverPrice=Number(body.silver_price??oldSnap.prices?.silver??0);if((standard==='GOLD'&&goldPrice<=0)||(standard==='SILVER'&&silverPrice<=0))throw new Error('NISAB_PRICE_REQUIRED');
 const nisabValue=new Decimal(standard==='GOLD'?85:595).mul(standard==='GOLD'?goldPrice:silverPrice);
 const{data:oldLines,error:oldLineError}=await supabase.from('zakat_assessment_lines').select('id,lot_id,quantity,market_value,valuation_price,valuation_currency,fx_rate,lots(id,acquisition_date,hawl_start_date,remaining_quantity,remaining_value_base,asset_accounts(name,asset_type,is_zakatable,metadata))').eq('assessment_id',id);if(oldLineError)throw oldLineError;
 const existingByLot=new Map<string,any>((oldLines??[]).map((x:any)=>[x.lot_id,x])),previousLotIds=new Set(existingByLot.keys());
 const rebuildFromCurrentLots=Boolean(linkedCycle?.assessment_id===id);
 let sourceLots:any[]=[];
 if(rebuildFromCurrentLots){const{data:lots,error:le}=await supabase.from('lots').select('id,acquisition_date,remaining_quantity,remaining_value_base,hawl_start_date,asset_accounts(name,asset_type,is_zakatable,metadata)').eq('user_id',user.id).gt('remaining_quantity',0).lte('acquisition_date',assessmentDate);if(le)throw le;sourceLots=(lots??[]).filter((lot:any)=>lot.asset_accounts?.is_zakatable===true&&!!lot.hawl_start_date)}
 else sourceLots=(oldLines??[]).map((l:any)=>{const lot=Array.isArray(l.lots)?l.lots[0]:l.lots;return lot?{...lot,remaining_quantity:l.quantity,remaining_value_base:l.market_value,_old_line:l}:null}).filter(Boolean);
 const candidates=sourceLots.map((lot:any)=>{const a=Array.isArray(lot.asset_accounts)?lot.asset_accounts[0]:lot.asset_accounts;let value=new Decimal(lot.remaining_value_base||0);if(a?.asset_type==='GOLD'&&goldPrice>0){const k=Number(a.metadata?.karat??24),p=k>0&&k<=24?k/24:1;value=new Decimal(lot.remaining_quantity||0).mul(goldPrice).mul(p)}else if(a?.asset_type==='SILVER'&&silverPrice>0){const raw=Number(a.metadata?.purity??a.metadata?.karat??999),p0=raw>1?raw/1000:raw,p=p0>0&&p0<=1?p0:1;value=new Decimal(lot.remaining_quantity||0).mul(silverPrice).mul(p)}else if(!rebuildFromCurrentLots&&lot._old_line){value=new Decimal(lot._old_line.market_value||0)}else{value=new Decimal(a?.metadata?.market_value??a?.metadata?.estimated_value??lot.remaining_value_base??0)}const start=lot.hawl_start_date;const hawl=calculateHawl(method.calendar_type==='GREGORIAN'?'GREGORIAN':'HIJRI_TABULAR',new Date(start+'T00:00:00Z'),new Date(assessmentDate+'T00:00:00Z'));return{lotId:lot.id,assetName:a?.name,assetType:a?.asset_type,quantity:lot.remaining_quantity,marketValueBase:value,hawlCompleted:Boolean(hawl.completed),hawlDueDate:hawl.dueDate.toISOString().slice(0,10),valuationPrice:a?.asset_type==='GOLD'?goldPrice:a?.asset_type==='SILVER'?silverPrice:(lot._old_line?.valuation_price??null),valuationCurrency:lot._old_line?.valuation_currency??old.currency,fxRate:Number(lot._old_line?.fx_rate??1)}}).filter((x:any)=>x.marketValueBase.gt(0));
 const currentLotIds=new Set(candidates.map((x:any)=>x.lotId)),addedLotIds=candidates.filter((x:any)=>!previousLotIds.has(x.lotId)).map((x:any)=>x.lotId),removedLotIds=Array.from(previousLotIds).filter((lotId:any)=>!currentLotIds.has(lotId));
 if(removedLotIds.length){const removedLineIds=removedLotIds.map((lotId:any)=>existingByLot.get(lotId)?.id).filter(Boolean);const{data:linkedAlloc,error:allocError}=await supabase.from('zakat_payment_allocations').select('assessment_line_id').eq('user_id',user.id).in('assessment_line_id',removedLineIds);if(allocError)throw allocError;if((linkedAlloc??[]).length)return NextResponse.json({error:'RECALCULATION_REMOVES_ALLOCATED_LINE',removed_lots:removedLotIds},{status:409})}
 const calc=calculateAssessment(candidates,nisabValue,method.zakat_rate);
 for(let i=0;i<candidates.length;i++){const c=candidates[i],r=calc.lines[i],payload={quantity:c.quantity,valuation_price:c.valuationPrice,valuation_currency:c.valuationCurrency,fx_rate:c.fxRate,market_value:c.marketValueBase.toString(),eligible_value:r.eligibleValue.toString(),zakat_amount:r.zakatAmount.toString(),eligibility_status:r.status,reason_code:r.status,explanation:`${c.assetName??'Asset'} → Lot ${c.lotId}: ${r.explanation}`},existing=existingByLot.get(c.lotId);if(existing){const{error:lineError}=await supabase.from('zakat_assessment_lines').update(payload).eq('id',existing.id).eq('assessment_id',id);if(lineError)throw lineError}else{const{error:lineError}=await supabase.from('zakat_assessment_lines').insert({assessment_id:id,lot_id:c.lotId,...payload});if(lineError)throw lineError}}
 if(removedLotIds.length){const{error:removeLineError}=await supabase.from('zakat_assessment_lines').delete().eq('assessment_id',id).in('lot_id',removedLotIds);if(removeLineError)throw removeLineError}
 const snapshot={...oldSnap,assessmentDate,valuationDate,methodCode:method.code,methodVersion:method.version,calendarType:method.calendar_type,nisabStandard:standard,nisabValue:nisabValue.toString(),priceMode,priceSource:typeof body.price_source==='string'?body.price_source:oldSnap.priceSource,prices:{gold:goldPrice,silver:silverPrice},recalculatedInPlaceAt:new Date().toISOString(),recalculatedFromAssessmentId:id,candidateLots:candidates.length,rebuildSource:rebuildFromCurrentLots?'CURRENT_LOTS':'EXISTING_SNAPSHOT_LINES',lateAddedLotsIncluded:addedLotIds.length>0,addedLotIds,removedLotIds};
 const update={assessment_date:assessmentDate,valuation_date:valuationDate,method_id:methodId,nisab_standard:standard,nisab_quantity:standard==='GOLD'?85:595,nisab_value_base:nisabValue.toString(),total_zakatable_value:calc.totalEligibleValue.toString(),zakat_rate:method.zakat_rate,zakat_due:calc.zakatDue.toString(),method_version:method.version,calculation_snapshot:snapshot};
 const{data,error:ue}=await supabase.from('zakat_assessments').update(update).eq('id',id).eq('user_id',user.id).select().single();if(ue)throw ue;
 if(old.hawl_cycle_id&&linkedCycle?.assessment_id===id)await supabase.from('zakat_hawl_cycles').update({valuation_date:valuationDate,nisab_value_base:nisabValue.toString(),snapshot:{latestAssessmentId:id,latestAssessmentDate:assessmentDate,recalculatedInPlaceAt:new Date().toISOString(),addedLotIds}}).eq('id',old.hawl_cycle_id).eq('user_id',user.id);
 await supabase.from('audit_logs').insert({user_id:user.id,entity_type:'zakat_assessment',entity_id:id,action:'RECALCULATE_IN_PLACE',old_data:old,new_data:{assessment:data,recalculation_delta:{source:rebuildFromCurrentLots?'CURRENT_LOTS':'EXISTING_SNAPSHOT_LINES',added_lot_ids:addedLotIds,removed_lot_ids:removedLotIds}}});
 return NextResponse.json({ok:true,assessment:data,lines_updated:candidates.length,added_lots:addedLotIds.length,removed_lots:removedLotIds.length,rebuild_source:rebuildFromCurrentLots?'CURRENT_LOTS':'EXISTING_SNAPSHOT_LINES'});
 }catch(e:any){return NextResponse.json({error:e.message},{status:e.message==='UNAUTHORIZED'?401:400})}}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){try{const{id}=await params;const{supabase,user}=await requireUser();const{data:a,error}=await supabase.from('zakat_assessments').select('id,status,hawl_cycle_id').eq('id',id).eq('user_id',user.id).single();if(error||!a)throw new Error('ASSESSMENT_NOT_FOUND');const[{count:payments},{count:allocations},{count:finalRefs}]=await Promise.all([supabase.from('zakat_payments').select('id',{count:'exact',head:true}).eq('user_id',user.id).eq('assessment_id',id),supabase.from('zakat_payment_allocations').select('id',{count:'exact',head:true}).eq('user_id',user.id).eq('assessment_id',id),supabase.from('zakat_hawl_cycles').select('id',{count:'exact',head:true}).eq('user_id',user.id).eq('final_assessment_id',id)]);if((payments||0)>0||(allocations||0)>0||(finalRefs||0)>0)return NextResponse.json({error:'ASSESSMENT_PROTECTED',reason:'PAYMENT_OR_FINAL_CYCLE_LINK'},{status:409});const{error:lineError}=await supabase.from('zakat_assessment_lines').delete().eq('assessment_id',id);if(lineError)throw lineError;const{error:deleteError}=await supabase.from('zakat_assessments').delete().eq('id',id).eq('user_id',user.id);if(deleteError)throw deleteError;await supabase.from('audit_logs').insert({user_id:user.id,entity_type:'zakat_assessment',entity_id:id,action:'DELETE_UNUSED_ASSESSMENT',old_data:a});return NextResponse.json({ok:true,id})}catch(e:any){return NextResponse.json({error:e.message},{status:e.message==='UNAUTHORIZED'?401:400})}}
