import Link from 'next/link';
const steps=[
 ['🔐','إنشاء الحساب وتسجيل الدخول','Create account & sign in','سجّل بالبريد الإلكتروني أو استخدم خيارات الدخول المتاحة، ثم انتقل إلى لوحة التحكم.','Sign in with email or an available social option, then continue to your dashboard.'],
 ['💼','إضافة الأصول','Add your assets','من قسم الأصول اختر النوع: نقد، بنك، ذهب، فضة، أسهم، مخزون، ذمم أو عقار. أدخل تاريخ التملك والقيمة أو الكمية والأسعار.','Choose an asset type: cash, bank, gold, silver, stocks, inventory, receivables or real estate. Enter acquisition date, value or quantity and prices.'],
 ['🟡','مثال: إضافة الذهب','Example: add gold','اختر ذهب، ثم أدخل الوزن بالغرام، العيار، سعر الشراء وسعر السوق. سيعرض النظام التكلفة والقيمة الحالية ومتابعة الحول.','Choose Gold, then enter weight in grams, karat, purchase price and market price. The system tracks cost, current value and hawl.'],
 ['📒','تسجيل الحركات','Record transactions','استخدم سجل المعاملات لإضافة عمليات الشراء والبيع والإضافة والسحب والتعديلات مع الاحتفاظ بأثر قابل للمراجعة.','Use the ledger for purchases, sales, additions, withdrawals and adjustments while keeping an auditable history.'],
 ['◷','متابعة الحول','Track Hawl','يعرض قسم الأصول مدة تملك كل أصل، الأصول التي اكتمل حولها، والتنبيهات للأصول التي اقترب موعدها.','The assets view shows holding duration, completed hawl and assets approaching their due date.'],
 ['🕌','احتساب الزكاة','Calculate Zakat','راجع الأصول الزكوية ثم انتقل إلى قسم الزكاة لإنشاء الاحتساب. القيمة الظاهرة في الأصول تساعدك في المتابعة، والاحتساب النهائي يتم من خلال محرك الزكاة.','Review zakatable assets, then use the Zakat section to create an assessment. Asset values support monitoring; final liability is calculated by the assessment engine.'],
 ['✓','تسجيل الزكاة المدفوعة','Record Zakat paid','بعد السداد، سجّل الدفعة ليظهر أمامك المستحق والمدفوع والمتبقي بصورة واضحة.','After payment, record it so due, paid and remaining amounts are clearly visible.'],
 ['📊','التقارير','Reports','استخدم التقارير لمراجعة الأصول والحركات والاحتسابات والمدفوعات، وللحصول على سجل منظم قابل للتدقيق.','Use reports to review assets, transactions, assessments and payments and maintain an organized audit trail.']
];
export default async function Guide({params}:{params:Promise<{locale:string}>}){const{locale}=await params,ar=locale==='ar';return <main className="container guide-page"><div className="guide-hero"><div><span className="guide-badge">? {ar?'دليل المستخدم':'User Guide'}</span><h1>{ar?'دليلك السريع لاستخدام ZakatFlow':'Your quick guide to ZakatFlow'}</h1><p>{ar?'اتبع الخطوات المصورة من إنشاء الحساب وحتى احتساب الزكاة وتسجيل السداد.':'Follow the visual steps from account setup through Zakat assessment and payment.'}</p></div><div className="guide-visual"><div className="guide-logo">Z</div><div><strong>ZakatFlow</strong><small>{ar?'إدارة الأصول والزكاة بوضوح':'Clear asset & Zakat management'}</small></div></div></div><div className="guide-flow"><span>🔐</span><b>→</b><span>💼</span><b>→</b><span>◷</span><b>→</b><span>🕌</span><b>→</b><span>✓</span><b>→</b><span>📊</span></div><section className="guide-grid">{steps.map((s,i)=><article className="guide-card" key={s[1]}><div className="guide-step"><span>{i+1}</span>{ar?'الخطوة':'Step'}</div><div className="guide-picture"><span>{s[0]}</span><div className="mock-lines"><i/><i/><i/></div></div><h2>{ar?s[1]:s[2]}</h2><p>{ar?s[3]:s[4]}</p>{i===1&&<Link className="btn secondary" href={`/${locale}/assets`}>{ar?'فتح الأصول ←':'Open assets →'}</Link>}{i===5&&<Link className="btn secondary" href={`/${locale}/assessments`}>{ar?'فتح الزكاة ←':'Open Zakat →'}</Link>}{i===7&&<Link className="btn secondary" href={`/${locale}/reports`}>{ar?'فتح التقارير ←':'Open reports →'}</Link>}</article>)}</section><section className="card section guide-tip"><div className="guide-tip-icon">💡</div><div><h2>{ar?'نصيحة للبداية':'Getting started tip'}</h2><p>{ar?'ابدأ بإدخال الأصول الحالية وتواريخ تملكها أولاً. بعد ذلك راجع الحول والقيم، ثم أنشئ احتساب الزكاة. بهذه الطريقة تحصل على نتيجة منظمة وأسهل للمراجعة.':'Start by entering your current assets and acquisition dates. Then review hawl and values before creating a Zakat assessment for a cleaner, easier-to-review result.'}</p></div></section></main>}
